import type { Media } from '@/payload-types'
import { getCdnMediaUrl, getMediaUrl } from '@/utilities/getMediaUrl'
import { STREAK_LOOK_REVISION, type StreakLookId } from './looks'

/**
 * Code-owned preset stills. One per look and polarity, rendered with alpha so
 * the CSS ground beneath (a Section band, the hero's `bg-background`) owns the
 * color and the still matches the live field's composite. They represent the
 * look, not any one entry's seed; an approved `posterMedia` upload replaces
 * them when an editor needs specific artwork.
 *
 * Files live in `public/images/streak-field/<look>-<surface>.webp` at
 * `STREAK_POSTER_SIZE`, regenerated by `scripts/streak-field-posters.ts`.
 * The revision query keys the optimizer cache to the look revision.
 */
export const STREAK_POSTER_SIZE = { width: 1600, height: 900 } as const

export type StreakPosterSurface = 'dark' | 'light'

export const streakPosterSrc = (look: StreakLookId, surface: StreakPosterSurface): string =>
  `/images/streak-field/${look}-${surface}.webp?v=${STREAK_LOOK_REVISION}`

/** MIME the menu and social fallbacks report for a preset poster. */
export const STREAK_POSTER_MIME = 'image/webp'

export type PosterImage = {
  src: string
  width: number
  height: number
  mime: string
  alt: string
}

/** The optimized URL for an approved poster upload, through the CDN path images use. */
export const mediaPosterImage = (media: Media): PosterImage | null => {
  const src =
    getCdnMediaUrl(media.filename, media.updatedAt) || getMediaUrl(media.url, media.updatedAt)
  if (!src) return null
  return {
    src,
    width: media.width ?? STREAK_POSTER_SIZE.width,
    height: media.height ?? STREAK_POSTER_SIZE.height,
    mime: media.mimeType ?? 'image/*',
    alt: '',
  }
}

export const presetPosterImage = (
  look: StreakLookId,
  surface: StreakPosterSurface,
): PosterImage => ({
  src: streakPosterSrc(look, surface),
  width: STREAK_POSTER_SIZE.width,
  height: STREAK_POSTER_SIZE.height,
  mime: STREAK_POSTER_MIME,
  alt: '',
})
