import { getCdnMediaUrl, getMediaUrl } from '@/utilities/getMediaUrl'
import { type Effect, lookPosterSrc } from '../studio/effect'
import { EFFECTS } from '../studio/effects'
import type { EffectVisual, PosterMediaSource } from './descriptor'

/**
 * Code-owned preset stills. One per look and polarity, rendered with alpha so
 * the CSS ground beneath (a Section band, the hero's `bg-background`) owns the
 * color and the still matches the live field's composite. They represent the
 * look, not any one entry's seed; an approved `posterMedia` upload replaces
 * them when an editor needs specific artwork.
 *
 * Files live in `public/images/<effect's posterDirectory>/<look>-<surface>.webp`
 * at `STREAK_POSTER_SIZE`, regenerated by `scripts/visual-posters.ts`. The
 * revision query keys the optimizer cache to the effect's look revision. An
 * effect that draws an opaque frame (`Effect.blend`) ships opaque stills, and
 * the slot composites them the way it composites the canvas.
 */
export const STREAK_POSTER_SIZE = { width: 1600, height: 900 } as const

export type StreakPosterSurface = 'dark' | 'light'

/** MIME the menu and social fallbacks report for a preset poster. */
export const STREAK_POSTER_MIME = 'image/webp'

export type PosterImage = {
  src: string
  width: number
  height: number
  mime: string
  alt: string
}

/** The optimized URL for an approved poster upload, through the CDN path images use. */
export const mediaPosterImage = (media: PosterMediaSource): PosterImage | null => {
  const src =
    getCdnMediaUrl(media.filename, media.updatedAt) || getMediaUrl(media.url, media.updatedAt)
  if (!src) return null
  return {
    src,
    width: media.width ?? STREAK_POSTER_SIZE.width,
    height: media.height ?? STREAK_POSTER_SIZE.height,
    mime: media.mimeType ?? 'image/*',
    alt: '',
  }
}

export const presetPosterImage = (
  effect: Effect,
  look: string,
  surface: StreakPosterSurface,
): PosterImage => ({
  src: lookPosterSrc(effect, look, surface),
  width: STREAK_POSTER_SIZE.width,
  height: STREAK_POSTER_SIZE.height,
  mime: STREAK_POSTER_MIME,
  alt: '',
})

export type VisualPosters = { light: PosterImage; dark: PosterImage; single: boolean }

/**
 * One poster resolver serves page slots and takeover-menu previews, for every
 * effect: the editor's upload wins, then the published Studio look's rendered
 * stills, then the shipped look's.
 */
export function visualPosters({ kind, descriptor }: EffectVisual): VisualPosters {
  const upload = descriptor.posterMedia ? mediaPosterImage(descriptor.posterMedia) : null
  if (upload) return { light: upload, dark: upload, single: true }
  const still = (surface: StreakPosterSurface) =>
    (descriptor.release && mediaPosterImage(descriptor.release.posters[surface])) ||
    presetPosterImage(EFFECTS[kind], descriptor.look, surface)
  return { light: still('light'), dark: still('dark'), single: false }
}
