import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_visual_surface" AS ENUM('auto', 'dark', 'light');
  ALTER TABLE "pages_full_media" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "pages_media_split" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "pages_split_narrow" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "pages_aud_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "pages" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "pages" ADD COLUMN "menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__pages_v_full_media_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__pages_v_media_split_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__pages_v_split_narrow_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_pages_v" ADD COLUMN "version_menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "posts_full_media" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "posts_media_split" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "posts_split_narrow" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "posts" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__posts_v_full_media_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__posts_v_media_split_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__posts_v_split_narrow_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_posts_v" ADD COLUMN "version_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "work_pages_full_media" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "work_pages_media_split" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "work_pages_split_narrow" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "work_pages_aud_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "work_pages" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "work_pages" ADD COLUMN "menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__work_pages_v_full_media_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__work_pages_v_media_split_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__work_pages_v_split_narrow_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_work_pages_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_work_pages_v" ADD COLUMN "version_menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "lab_pages_full_media" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "lab_pages_media_split" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "lab_pages_split_narrow" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "lab_pages" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__lab_pages_v_full_media_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__lab_pages_v_media_split_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__lab_pages_v_split_narrow_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_lab_pages_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "expertise_pages_full_media" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "expertise_pages_media_split" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "expertise_pages_split_narrow" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "expertise_pages_aud_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "expertise_pages" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "expertise_pages" ADD COLUMN "menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__expertise_pages_v_full_media_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__expertise_pages_v_media_split_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__expertise_pages_v_split_narrow_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_expertise_pages_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_expertise_pages_v" ADD COLUMN "version_menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "audience_pages_full_media" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "audience_pages_media_split" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "audience_pages_split_narrow" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "audience_pages_aud_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "audience_pages" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "audience_pages" ADD COLUMN "menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__audience_pages_v_full_media_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__audience_pages_v_media_split_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__audience_pages_v_split_narrow_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_audience_pages_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_audience_pages_v" ADD COLUMN "version_menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "contact_pages" ADD COLUMN "menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_contact_pages_v" ADD COLUMN "version_menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "home_full_media" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "home_media_split" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "home_split_narrow" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "home_aud_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "home" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__home_v_full_media_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__home_v_media_split_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__home_v_split_narrow_v" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "__home_v_aud_tabs_v_tabs" ADD COLUMN "shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_home_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "insights_index" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "insights_index" ADD COLUMN "menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_insights_index_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_insights_index_v" ADD COLUMN "version_menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "lab_index" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "lab_index" ADD COLUMN "menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_lab_index_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_lab_index_v" ADD COLUMN "version_menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "works_index" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "works_index" ADD COLUMN "menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_works_index_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_works_index_v" ADD COLUMN "version_menu_preview_shader_surface" "enum_visual_surface" DEFAULT 'auto';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_full_media" DROP COLUMN "shader_surface";
  ALTER TABLE "pages_media_split" DROP COLUMN "shader_surface";
  ALTER TABLE "pages_split_narrow" DROP COLUMN "shader_surface";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "pages_aud_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "pages" DROP COLUMN "menu_preview_shader_surface";
  ALTER TABLE "__pages_v_full_media_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__pages_v_media_split_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__pages_v_split_narrow_v" DROP COLUMN "shader_surface";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "_pages_v" DROP COLUMN "version_menu_preview_shader_surface";
  ALTER TABLE "posts_full_media" DROP COLUMN "shader_surface";
  ALTER TABLE "posts_media_split" DROP COLUMN "shader_surface";
  ALTER TABLE "posts_split_narrow" DROP COLUMN "shader_surface";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "posts" DROP COLUMN "shader_surface";
  ALTER TABLE "__posts_v_full_media_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__posts_v_media_split_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__posts_v_split_narrow_v" DROP COLUMN "shader_surface";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "_posts_v" DROP COLUMN "version_shader_surface";
  ALTER TABLE "work_pages_full_media" DROP COLUMN "shader_surface";
  ALTER TABLE "work_pages_media_split" DROP COLUMN "shader_surface";
  ALTER TABLE "work_pages_split_narrow" DROP COLUMN "shader_surface";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "work_pages_aud_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "work_pages" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "work_pages" DROP COLUMN "menu_preview_shader_surface";
  ALTER TABLE "__work_pages_v_full_media_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__work_pages_v_media_split_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__work_pages_v_split_narrow_v" DROP COLUMN "shader_surface";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "_work_pages_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "_work_pages_v" DROP COLUMN "version_menu_preview_shader_surface";
  ALTER TABLE "lab_pages_full_media" DROP COLUMN "shader_surface";
  ALTER TABLE "lab_pages_media_split" DROP COLUMN "shader_surface";
  ALTER TABLE "lab_pages_split_narrow" DROP COLUMN "shader_surface";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "lab_pages" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "__lab_pages_v_full_media_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__lab_pages_v_media_split_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__lab_pages_v_split_narrow_v" DROP COLUMN "shader_surface";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "_lab_pages_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "expertise_pages_full_media" DROP COLUMN "shader_surface";
  ALTER TABLE "expertise_pages_media_split" DROP COLUMN "shader_surface";
  ALTER TABLE "expertise_pages_split_narrow" DROP COLUMN "shader_surface";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "expertise_pages_aud_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "expertise_pages" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "expertise_pages" DROP COLUMN "menu_preview_shader_surface";
  ALTER TABLE "__expertise_pages_v_full_media_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__expertise_pages_v_media_split_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__expertise_pages_v_split_narrow_v" DROP COLUMN "shader_surface";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "_expertise_pages_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "_expertise_pages_v" DROP COLUMN "version_menu_preview_shader_surface";
  ALTER TABLE "audience_pages_full_media" DROP COLUMN "shader_surface";
  ALTER TABLE "audience_pages_media_split" DROP COLUMN "shader_surface";
  ALTER TABLE "audience_pages_split_narrow" DROP COLUMN "shader_surface";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "audience_pages_aud_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "audience_pages" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "audience_pages" DROP COLUMN "menu_preview_shader_surface";
  ALTER TABLE "__audience_pages_v_full_media_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__audience_pages_v_media_split_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__audience_pages_v_split_narrow_v" DROP COLUMN "shader_surface";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "_audience_pages_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "_audience_pages_v" DROP COLUMN "version_menu_preview_shader_surface";
  ALTER TABLE "contact_pages" DROP COLUMN "menu_preview_shader_surface";
  ALTER TABLE "_contact_pages_v" DROP COLUMN "version_menu_preview_shader_surface";
  ALTER TABLE "home_full_media" DROP COLUMN "shader_surface";
  ALTER TABLE "home_media_split" DROP COLUMN "shader_surface";
  ALTER TABLE "home_split_narrow" DROP COLUMN "shader_surface";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "home_aud_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "home" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "__home_v_full_media_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__home_v_media_split_v" DROP COLUMN "shader_surface";
  ALTER TABLE "__home_v_split_narrow_v" DROP COLUMN "shader_surface";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "__home_v_aud_tabs_v_tabs" DROP COLUMN "shader_surface";
  ALTER TABLE "_home_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "insights_index" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "insights_index" DROP COLUMN "menu_preview_shader_surface";
  ALTER TABLE "_insights_index_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "_insights_index_v" DROP COLUMN "version_menu_preview_shader_surface";
  ALTER TABLE "lab_index" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "lab_index" DROP COLUMN "menu_preview_shader_surface";
  ALTER TABLE "_lab_index_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "_lab_index_v" DROP COLUMN "version_menu_preview_shader_surface";
  ALTER TABLE "works_index" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "works_index" DROP COLUMN "menu_preview_shader_surface";
  ALTER TABLE "_works_index_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "_works_index_v" DROP COLUMN "version_menu_preview_shader_surface";
  DROP TYPE "public"."enum_visual_surface";`)
}
