import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_leak_hover_targets" AS ENUM('interactive', 'marked');
  ALTER TABLE "pages_full_media" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "pages_full_media" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "pages_media_split" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "pages_media_split" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "pages_split_narrow" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "pages_split_narrow" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "pages" ADD COLUMN "hero_shader_section_hover" numeric;
  ALTER TABLE "__pages_v_full_media_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__pages_v_full_media_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__pages_v_media_split_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__pages_v_media_split_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__pages_v_split_narrow_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__pages_v_split_narrow_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_section_hover" numeric;
  ALTER TABLE "posts_full_media" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "posts_full_media" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "posts_media_split" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "posts_media_split" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "posts_split_narrow" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "posts_split_narrow" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__posts_v_full_media_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__posts_v_full_media_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__posts_v_media_split_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__posts_v_media_split_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__posts_v_split_narrow_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__posts_v_split_narrow_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "work_pages_full_media" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "work_pages_full_media" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "work_pages_media_split" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "work_pages_media_split" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "work_pages_split_narrow" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "work_pages_split_narrow" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "work_pages" ADD COLUMN "hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "work_pages" ADD COLUMN "hero_shader_section_hover" numeric;
  ALTER TABLE "__work_pages_v_full_media_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__work_pages_v_full_media_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__work_pages_v_media_split_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__work_pages_v_media_split_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__work_pages_v_split_narrow_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__work_pages_v_split_narrow_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_work_pages_v" ADD COLUMN "version_hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_work_pages_v" ADD COLUMN "version_hero_shader_section_hover" numeric;
  ALTER TABLE "lab_pages_full_media" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "lab_pages_full_media" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "lab_pages_media_split" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "lab_pages_media_split" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "lab_pages_split_narrow" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "lab_pages_split_narrow" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "lab_pages" ADD COLUMN "hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "lab_pages" ADD COLUMN "hero_shader_section_hover" numeric;
  ALTER TABLE "__lab_pages_v_full_media_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__lab_pages_v_full_media_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__lab_pages_v_media_split_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__lab_pages_v_media_split_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__lab_pages_v_split_narrow_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__lab_pages_v_split_narrow_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_lab_pages_v" ADD COLUMN "version_hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_lab_pages_v" ADD COLUMN "version_hero_shader_section_hover" numeric;
  ALTER TABLE "expertise_pages_full_media" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "expertise_pages_full_media" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "expertise_pages_media_split" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "expertise_pages_media_split" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "expertise_pages_split_narrow" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "expertise_pages_split_narrow" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "expertise_pages" ADD COLUMN "hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "expertise_pages" ADD COLUMN "hero_shader_section_hover" numeric;
  ALTER TABLE "__expertise_pages_v_full_media_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__expertise_pages_v_full_media_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__expertise_pages_v_media_split_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__expertise_pages_v_media_split_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__expertise_pages_v_split_narrow_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__expertise_pages_v_split_narrow_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_expertise_pages_v" ADD COLUMN "version_hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_expertise_pages_v" ADD COLUMN "version_hero_shader_section_hover" numeric;
  ALTER TABLE "audience_pages_full_media" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "audience_pages_full_media" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "audience_pages_media_split" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "audience_pages_media_split" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "audience_pages_split_narrow" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "audience_pages_split_narrow" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "audience_pages" ADD COLUMN "hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "audience_pages" ADD COLUMN "hero_shader_section_hover" numeric;
  ALTER TABLE "__audience_pages_v_full_media_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__audience_pages_v_full_media_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__audience_pages_v_media_split_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__audience_pages_v_media_split_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__audience_pages_v_split_narrow_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__audience_pages_v_split_narrow_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_audience_pages_v" ADD COLUMN "version_hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_audience_pages_v" ADD COLUMN "version_hero_shader_section_hover" numeric;
  ALTER TABLE "home_full_media" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "home_full_media" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "home_media_split" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "home_media_split" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "home_split_narrow" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "home_split_narrow" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__home_v_full_media_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__home_v_full_media_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__home_v_media_split_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__home_v_media_split_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "__home_v_split_narrow_v" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "__home_v_split_narrow_v" ADD COLUMN "shader_section_hover" numeric;
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_section_hover" numeric;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_full_media" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "pages_full_media" DROP COLUMN "shader_section_hover";
  ALTER TABLE "pages_media_split" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "pages_media_split" DROP COLUMN "shader_section_hover";
  ALTER TABLE "pages_split_narrow" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "pages_split_narrow" DROP COLUMN "shader_section_hover";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_hover_targets";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_section_hover";
  ALTER TABLE "__pages_v_full_media_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__pages_v_full_media_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__pages_v_media_split_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__pages_v_media_split_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__pages_v_split_narrow_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__pages_v_split_narrow_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_hover_targets";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_section_hover";
  ALTER TABLE "posts_full_media" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "posts_full_media" DROP COLUMN "shader_section_hover";
  ALTER TABLE "posts_media_split" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "posts_media_split" DROP COLUMN "shader_section_hover";
  ALTER TABLE "posts_split_narrow" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "posts_split_narrow" DROP COLUMN "shader_section_hover";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__posts_v_full_media_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__posts_v_full_media_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__posts_v_media_split_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__posts_v_media_split_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__posts_v_split_narrow_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__posts_v_split_narrow_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "work_pages_full_media" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "work_pages_full_media" DROP COLUMN "shader_section_hover";
  ALTER TABLE "work_pages_media_split" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "work_pages_media_split" DROP COLUMN "shader_section_hover";
  ALTER TABLE "work_pages_split_narrow" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "work_pages_split_narrow" DROP COLUMN "shader_section_hover";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "work_pages" DROP COLUMN "hero_shader_hover_targets";
  ALTER TABLE "work_pages" DROP COLUMN "hero_shader_section_hover";
  ALTER TABLE "__work_pages_v_full_media_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__work_pages_v_full_media_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__work_pages_v_media_split_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__work_pages_v_media_split_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__work_pages_v_split_narrow_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__work_pages_v_split_narrow_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_work_pages_v" DROP COLUMN "version_hero_shader_hover_targets";
  ALTER TABLE "_work_pages_v" DROP COLUMN "version_hero_shader_section_hover";
  ALTER TABLE "lab_pages_full_media" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "lab_pages_full_media" DROP COLUMN "shader_section_hover";
  ALTER TABLE "lab_pages_media_split" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "lab_pages_media_split" DROP COLUMN "shader_section_hover";
  ALTER TABLE "lab_pages_split_narrow" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "lab_pages_split_narrow" DROP COLUMN "shader_section_hover";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "lab_pages" DROP COLUMN "hero_shader_hover_targets";
  ALTER TABLE "lab_pages" DROP COLUMN "hero_shader_section_hover";
  ALTER TABLE "__lab_pages_v_full_media_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__lab_pages_v_full_media_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__lab_pages_v_media_split_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__lab_pages_v_media_split_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__lab_pages_v_split_narrow_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__lab_pages_v_split_narrow_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_lab_pages_v" DROP COLUMN "version_hero_shader_hover_targets";
  ALTER TABLE "_lab_pages_v" DROP COLUMN "version_hero_shader_section_hover";
  ALTER TABLE "expertise_pages_full_media" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "expertise_pages_full_media" DROP COLUMN "shader_section_hover";
  ALTER TABLE "expertise_pages_media_split" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "expertise_pages_media_split" DROP COLUMN "shader_section_hover";
  ALTER TABLE "expertise_pages_split_narrow" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "expertise_pages_split_narrow" DROP COLUMN "shader_section_hover";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "expertise_pages" DROP COLUMN "hero_shader_hover_targets";
  ALTER TABLE "expertise_pages" DROP COLUMN "hero_shader_section_hover";
  ALTER TABLE "__expertise_pages_v_full_media_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__expertise_pages_v_full_media_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__expertise_pages_v_media_split_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__expertise_pages_v_media_split_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__expertise_pages_v_split_narrow_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__expertise_pages_v_split_narrow_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_expertise_pages_v" DROP COLUMN "version_hero_shader_hover_targets";
  ALTER TABLE "_expertise_pages_v" DROP COLUMN "version_hero_shader_section_hover";
  ALTER TABLE "audience_pages_full_media" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "audience_pages_full_media" DROP COLUMN "shader_section_hover";
  ALTER TABLE "audience_pages_media_split" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "audience_pages_media_split" DROP COLUMN "shader_section_hover";
  ALTER TABLE "audience_pages_split_narrow" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "audience_pages_split_narrow" DROP COLUMN "shader_section_hover";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "audience_pages" DROP COLUMN "hero_shader_hover_targets";
  ALTER TABLE "audience_pages" DROP COLUMN "hero_shader_section_hover";
  ALTER TABLE "__audience_pages_v_full_media_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__audience_pages_v_full_media_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__audience_pages_v_media_split_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__audience_pages_v_media_split_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__audience_pages_v_split_narrow_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__audience_pages_v_split_narrow_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_audience_pages_v" DROP COLUMN "version_hero_shader_hover_targets";
  ALTER TABLE "_audience_pages_v" DROP COLUMN "version_hero_shader_section_hover";
  ALTER TABLE "home_full_media" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "home_full_media" DROP COLUMN "shader_section_hover";
  ALTER TABLE "home_media_split" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "home_media_split" DROP COLUMN "shader_section_hover";
  ALTER TABLE "home_split_narrow" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "home_split_narrow" DROP COLUMN "shader_section_hover";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__home_v_full_media_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__home_v_full_media_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__home_v_media_split_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__home_v_media_split_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "__home_v_split_narrow_v" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "__home_v_split_narrow_v" DROP COLUMN "shader_section_hover";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_hover_targets";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_section_hover";
  DROP TYPE "public"."enum_leak_hover_targets";`)
}
