import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_full_media_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_pages_media_split_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_pages_split_narrow_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_pages_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___pages_v_full_media_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___pages_v_media_split_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___pages_v_split_narrow_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__pages_v_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_posts_full_media_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_posts_media_split_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_posts_split_narrow_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_posts_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___posts_v_full_media_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___posts_v_media_split_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___posts_v_split_narrow_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__posts_v_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_work_pages_full_media_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_work_pages_media_split_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_work_pages_split_narrow_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_work_pages_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___work_pages_v_full_media_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___work_pages_v_media_split_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___work_pages_v_split_narrow_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__work_pages_v_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_lab_pages_full_media_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_lab_pages_media_split_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_lab_pages_split_narrow_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_lab_pages_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___lab_pages_v_full_media_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___lab_pages_v_media_split_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___lab_pages_v_split_narrow_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__lab_pages_v_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_expertise_pages_full_media_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_expertise_pages_media_split_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_expertise_pages_split_narrow_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_expertise_pages_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___expertise_pages_v_full_media_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___expertise_pages_v_media_split_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___expertise_pages_v_split_narrow_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_audience_pages_full_media_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_audience_pages_media_split_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_audience_pages_split_narrow_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_audience_pages_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___audience_pages_v_full_media_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___audience_pages_v_media_split_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___audience_pages_v_split_narrow_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_streak_looks_effect" AS ENUM('streakField', 'lightLeak');
  CREATE TYPE "public"."enum__streak_looks_v_version_effect" AS ENUM('streakField', 'lightLeak');
  CREATE TYPE "public"."enum_home_full_media_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_home_media_split_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_home_split_narrow_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_home_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___home_v_full_media_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___home_v_media_split_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum___home_v_split_narrow_v_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__home_v_blocks_feature_tabs_tabs_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  ALTER TYPE "public"."enum_pages_full_media_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_pages_media_split_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_pages_split_narrow_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_pages_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___pages_v_full_media_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___pages_v_media_split_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___pages_v_split_narrow_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__pages_v_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_posts_full_media_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_posts_media_split_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_posts_split_narrow_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_posts_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___posts_v_full_media_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___posts_v_media_split_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___posts_v_split_narrow_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__posts_v_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_work_pages_full_media_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_work_pages_media_split_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_work_pages_split_narrow_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_work_pages_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___work_pages_v_full_media_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___work_pages_v_media_split_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___work_pages_v_split_narrow_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__work_pages_v_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_lab_pages_full_media_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_lab_pages_media_split_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_lab_pages_split_narrow_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_lab_pages_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___lab_pages_v_full_media_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___lab_pages_v_media_split_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___lab_pages_v_split_narrow_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__lab_pages_v_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_expertise_pages_full_media_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_expertise_pages_media_split_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_expertise_pages_split_narrow_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_expertise_pages_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___expertise_pages_v_full_media_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___expertise_pages_v_media_split_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___expertise_pages_v_split_narrow_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__expertise_pages_v_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_audience_pages_full_media_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_audience_pages_media_split_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_audience_pages_split_narrow_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_audience_pages_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___audience_pages_v_full_media_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___audience_pages_v_media_split_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___audience_pages_v_split_narrow_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__audience_pages_v_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_home_full_media_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_home_media_split_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_home_split_narrow_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_home_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___home_v_full_media_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___home_v_media_split_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum___home_v_split_narrow_v_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__home_v_blocks_feature_tabs_tabs_visual_type" ADD VALUE 'lightLeak';
  ALTER TABLE "pages_full_media" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "pages_full_media" ADD COLUMN "shader_origin" "enum_pages_full_media_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "pages_full_media" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "pages_media_split" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "pages_media_split" ADD COLUMN "shader_origin" "enum_pages_media_split_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "pages_media_split" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "pages_split_narrow" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "pages_split_narrow" ADD COLUMN "shader_origin" "enum_pages_split_narrow_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "pages_split_narrow" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum_pages_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__pages_v_full_media_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__pages_v_full_media_v" ADD COLUMN "shader_origin" "enum___pages_v_full_media_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__pages_v_full_media_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__pages_v_media_split_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__pages_v_media_split_v" ADD COLUMN "shader_origin" "enum___pages_v_media_split_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__pages_v_media_split_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__pages_v_split_narrow_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__pages_v_split_narrow_v" ADD COLUMN "shader_origin" "enum___pages_v_split_narrow_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__pages_v_split_narrow_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum__pages_v_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "posts_full_media" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "posts_full_media" ADD COLUMN "shader_origin" "enum_posts_full_media_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "posts_full_media" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "posts_media_split" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "posts_media_split" ADD COLUMN "shader_origin" "enum_posts_media_split_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "posts_media_split" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "posts_split_narrow" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "posts_split_narrow" ADD COLUMN "shader_origin" "enum_posts_split_narrow_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "posts_split_narrow" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum_posts_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__posts_v_full_media_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__posts_v_full_media_v" ADD COLUMN "shader_origin" "enum___posts_v_full_media_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__posts_v_full_media_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__posts_v_media_split_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__posts_v_media_split_v" ADD COLUMN "shader_origin" "enum___posts_v_media_split_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__posts_v_media_split_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__posts_v_split_narrow_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__posts_v_split_narrow_v" ADD COLUMN "shader_origin" "enum___posts_v_split_narrow_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__posts_v_split_narrow_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum__posts_v_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "work_pages_full_media" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "work_pages_full_media" ADD COLUMN "shader_origin" "enum_work_pages_full_media_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "work_pages_full_media" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "work_pages_media_split" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "work_pages_media_split" ADD COLUMN "shader_origin" "enum_work_pages_media_split_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "work_pages_media_split" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "work_pages_split_narrow" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "work_pages_split_narrow" ADD COLUMN "shader_origin" "enum_work_pages_split_narrow_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "work_pages_split_narrow" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum_work_pages_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__work_pages_v_full_media_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__work_pages_v_full_media_v" ADD COLUMN "shader_origin" "enum___work_pages_v_full_media_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__work_pages_v_full_media_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__work_pages_v_media_split_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__work_pages_v_media_split_v" ADD COLUMN "shader_origin" "enum___work_pages_v_media_split_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__work_pages_v_media_split_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__work_pages_v_split_narrow_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__work_pages_v_split_narrow_v" ADD COLUMN "shader_origin" "enum___work_pages_v_split_narrow_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__work_pages_v_split_narrow_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum__work_pages_v_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_full_media" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "lab_pages_full_media" ADD COLUMN "shader_origin" "enum_lab_pages_full_media_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "lab_pages_full_media" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_media_split" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "lab_pages_media_split" ADD COLUMN "shader_origin" "enum_lab_pages_media_split_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "lab_pages_media_split" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_split_narrow" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "lab_pages_split_narrow" ADD COLUMN "shader_origin" "enum_lab_pages_split_narrow_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "lab_pages_split_narrow" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum_lab_pages_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_full_media_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_full_media_v" ADD COLUMN "shader_origin" "enum___lab_pages_v_full_media_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__lab_pages_v_full_media_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_media_split_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_media_split_v" ADD COLUMN "shader_origin" "enum___lab_pages_v_media_split_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__lab_pages_v_media_split_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_split_narrow_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_split_narrow_v" ADD COLUMN "shader_origin" "enum___lab_pages_v_split_narrow_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__lab_pages_v_split_narrow_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum__lab_pages_v_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_full_media" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_full_media" ADD COLUMN "shader_origin" "enum_expertise_pages_full_media_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "expertise_pages_full_media" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_media_split" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_media_split" ADD COLUMN "shader_origin" "enum_expertise_pages_media_split_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "expertise_pages_media_split" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_split_narrow" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_split_narrow" ADD COLUMN "shader_origin" "enum_expertise_pages_split_narrow_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "expertise_pages_split_narrow" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum_expertise_pages_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_full_media_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_full_media_v" ADD COLUMN "shader_origin" "enum___expertise_pages_v_full_media_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__expertise_pages_v_full_media_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_media_split_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_media_split_v" ADD COLUMN "shader_origin" "enum___expertise_pages_v_media_split_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__expertise_pages_v_media_split_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_split_narrow_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_split_narrow_v" ADD COLUMN "shader_origin" "enum___expertise_pages_v_split_narrow_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__expertise_pages_v_split_narrow_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum__expertise_pages_v_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_full_media" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "audience_pages_full_media" ADD COLUMN "shader_origin" "enum_audience_pages_full_media_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "audience_pages_full_media" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_media_split" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "audience_pages_media_split" ADD COLUMN "shader_origin" "enum_audience_pages_media_split_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "audience_pages_media_split" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_split_narrow" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "audience_pages_split_narrow" ADD COLUMN "shader_origin" "enum_audience_pages_split_narrow_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "audience_pages_split_narrow" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum_audience_pages_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_full_media_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_full_media_v" ADD COLUMN "shader_origin" "enum___audience_pages_v_full_media_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__audience_pages_v_full_media_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_media_split_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_media_split_v" ADD COLUMN "shader_origin" "enum___audience_pages_v_media_split_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__audience_pages_v_media_split_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_split_narrow_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_split_narrow_v" ADD COLUMN "shader_origin" "enum___audience_pages_v_split_narrow_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__audience_pages_v_split_narrow_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum__audience_pages_v_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "streak_looks" ADD COLUMN "effect" "enum_streak_looks_effect" DEFAULT 'streakField';
  ALTER TABLE "_streak_looks_v" ADD COLUMN "version_effect" "enum__streak_looks_v_version_effect" DEFAULT 'streakField';
  ALTER TABLE "home_full_media" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "home_full_media" ADD COLUMN "shader_origin" "enum_home_full_media_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "home_full_media" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "home_media_split" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "home_media_split" ADD COLUMN "shader_origin" "enum_home_media_split_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "home_media_split" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "home_split_narrow" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "home_split_narrow" ADD COLUMN "shader_origin" "enum_home_split_narrow_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "home_split_narrow" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum_home_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__home_v_full_media_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__home_v_full_media_v" ADD COLUMN "shader_origin" "enum___home_v_full_media_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__home_v_full_media_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__home_v_media_split_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__home_v_media_split_v" ADD COLUMN "shader_origin" "enum___home_v_media_split_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__home_v_media_split_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "__home_v_split_narrow_v" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "__home_v_split_narrow_v" ADD COLUMN "shader_origin" "enum___home_v_split_narrow_v_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "__home_v_split_narrow_v" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_origin" "enum__home_v_blocks_feature_tabs_tabs_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_show_media" boolean DEFAULT false;
  CREATE INDEX "streak_looks_effect_idx" ON "streak_looks" USING btree ("effect");
  CREATE INDEX "_streak_looks_v_version_version_effect_idx" ON "_streak_looks_v" USING btree ("version_effect");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_full_media" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_full_media_visual_type";
  CREATE TYPE "public"."enum_pages_full_media_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "pages_full_media" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_pages_full_media_visual_type" USING "visual_type"::"public"."enum_pages_full_media_visual_type";
  ALTER TABLE "pages_media_split" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_media_split_visual_type";
  CREATE TYPE "public"."enum_pages_media_split_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "pages_media_split" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_pages_media_split_visual_type" USING "visual_type"::"public"."enum_pages_media_split_visual_type";
  ALTER TABLE "pages_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_split_narrow_visual_type";
  CREATE TYPE "public"."enum_pages_split_narrow_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "pages_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_pages_split_narrow_visual_type" USING "visual_type"::"public"."enum_pages_split_narrow_visual_type";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum_pages_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_pages_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum_pages_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "__pages_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___pages_v_full_media_v_visual_type";
  CREATE TYPE "public"."enum___pages_v_full_media_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__pages_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___pages_v_full_media_v_visual_type" USING "visual_type"::"public"."enum___pages_v_full_media_v_visual_type";
  ALTER TABLE "__pages_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___pages_v_media_split_v_visual_type";
  CREATE TYPE "public"."enum___pages_v_media_split_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__pages_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___pages_v_media_split_v_visual_type" USING "visual_type"::"public"."enum___pages_v_media_split_v_visual_type";
  ALTER TABLE "__pages_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___pages_v_split_narrow_v_visual_type";
  CREATE TYPE "public"."enum___pages_v_split_narrow_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__pages_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___pages_v_split_narrow_v_visual_type" USING "visual_type"::"public"."enum___pages_v_split_narrow_v_visual_type";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum__pages_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum__pages_v_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum__pages_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "posts_full_media" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_full_media_visual_type";
  CREATE TYPE "public"."enum_posts_full_media_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "posts_full_media" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_posts_full_media_visual_type" USING "visual_type"::"public"."enum_posts_full_media_visual_type";
  ALTER TABLE "posts_media_split" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_media_split_visual_type";
  CREATE TYPE "public"."enum_posts_media_split_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "posts_media_split" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_posts_media_split_visual_type" USING "visual_type"::"public"."enum_posts_media_split_visual_type";
  ALTER TABLE "posts_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_split_narrow_visual_type";
  CREATE TYPE "public"."enum_posts_split_narrow_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "posts_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_posts_split_narrow_visual_type" USING "visual_type"::"public"."enum_posts_split_narrow_visual_type";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum_posts_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_posts_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum_posts_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "__posts_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___posts_v_full_media_v_visual_type";
  CREATE TYPE "public"."enum___posts_v_full_media_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__posts_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___posts_v_full_media_v_visual_type" USING "visual_type"::"public"."enum___posts_v_full_media_v_visual_type";
  ALTER TABLE "__posts_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___posts_v_media_split_v_visual_type";
  CREATE TYPE "public"."enum___posts_v_media_split_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__posts_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___posts_v_media_split_v_visual_type" USING "visual_type"::"public"."enum___posts_v_media_split_v_visual_type";
  ALTER TABLE "__posts_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___posts_v_split_narrow_v_visual_type";
  CREATE TYPE "public"."enum___posts_v_split_narrow_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__posts_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___posts_v_split_narrow_v_visual_type" USING "visual_type"::"public"."enum___posts_v_split_narrow_v_visual_type";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__posts_v_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum__posts_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum__posts_v_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum__posts_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "work_pages_full_media" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_work_pages_full_media_visual_type";
  CREATE TYPE "public"."enum_work_pages_full_media_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "work_pages_full_media" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_work_pages_full_media_visual_type" USING "visual_type"::"public"."enum_work_pages_full_media_visual_type";
  ALTER TABLE "work_pages_media_split" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_work_pages_media_split_visual_type";
  CREATE TYPE "public"."enum_work_pages_media_split_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "work_pages_media_split" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_work_pages_media_split_visual_type" USING "visual_type"::"public"."enum_work_pages_media_split_visual_type";
  ALTER TABLE "work_pages_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_work_pages_split_narrow_visual_type";
  CREATE TYPE "public"."enum_work_pages_split_narrow_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "work_pages_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_work_pages_split_narrow_visual_type" USING "visual_type"::"public"."enum_work_pages_split_narrow_visual_type";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_work_pages_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum_work_pages_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_work_pages_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum_work_pages_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "__work_pages_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___work_pages_v_full_media_v_visual_type";
  CREATE TYPE "public"."enum___work_pages_v_full_media_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__work_pages_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___work_pages_v_full_media_v_visual_type" USING "visual_type"::"public"."enum___work_pages_v_full_media_v_visual_type";
  ALTER TABLE "__work_pages_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___work_pages_v_media_split_v_visual_type";
  CREATE TYPE "public"."enum___work_pages_v_media_split_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__work_pages_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___work_pages_v_media_split_v_visual_type" USING "visual_type"::"public"."enum___work_pages_v_media_split_v_visual_type";
  ALTER TABLE "__work_pages_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___work_pages_v_split_narrow_v_visual_type";
  CREATE TYPE "public"."enum___work_pages_v_split_narrow_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__work_pages_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___work_pages_v_split_narrow_v_visual_type" USING "visual_type"::"public"."enum___work_pages_v_split_narrow_v_visual_type";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__work_pages_v_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum__work_pages_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum__work_pages_v_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum__work_pages_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "lab_pages_full_media" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_lab_pages_full_media_visual_type";
  CREATE TYPE "public"."enum_lab_pages_full_media_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "lab_pages_full_media" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_lab_pages_full_media_visual_type" USING "visual_type"::"public"."enum_lab_pages_full_media_visual_type";
  ALTER TABLE "lab_pages_media_split" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_lab_pages_media_split_visual_type";
  CREATE TYPE "public"."enum_lab_pages_media_split_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "lab_pages_media_split" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_lab_pages_media_split_visual_type" USING "visual_type"::"public"."enum_lab_pages_media_split_visual_type";
  ALTER TABLE "lab_pages_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_lab_pages_split_narrow_visual_type";
  CREATE TYPE "public"."enum_lab_pages_split_narrow_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "lab_pages_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_lab_pages_split_narrow_visual_type" USING "visual_type"::"public"."enum_lab_pages_split_narrow_visual_type";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_lab_pages_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum_lab_pages_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_lab_pages_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum_lab_pages_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "__lab_pages_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___lab_pages_v_full_media_v_visual_type";
  CREATE TYPE "public"."enum___lab_pages_v_full_media_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__lab_pages_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___lab_pages_v_full_media_v_visual_type" USING "visual_type"::"public"."enum___lab_pages_v_full_media_v_visual_type";
  ALTER TABLE "__lab_pages_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___lab_pages_v_media_split_v_visual_type";
  CREATE TYPE "public"."enum___lab_pages_v_media_split_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__lab_pages_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___lab_pages_v_media_split_v_visual_type" USING "visual_type"::"public"."enum___lab_pages_v_media_split_v_visual_type";
  ALTER TABLE "__lab_pages_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___lab_pages_v_split_narrow_v_visual_type";
  CREATE TYPE "public"."enum___lab_pages_v_split_narrow_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__lab_pages_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___lab_pages_v_split_narrow_v_visual_type" USING "visual_type"::"public"."enum___lab_pages_v_split_narrow_v_visual_type";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__lab_pages_v_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum__lab_pages_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum__lab_pages_v_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum__lab_pages_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "expertise_pages_full_media" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_expertise_pages_full_media_visual_type";
  CREATE TYPE "public"."enum_expertise_pages_full_media_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "expertise_pages_full_media" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_expertise_pages_full_media_visual_type" USING "visual_type"::"public"."enum_expertise_pages_full_media_visual_type";
  ALTER TABLE "expertise_pages_media_split" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_expertise_pages_media_split_visual_type";
  CREATE TYPE "public"."enum_expertise_pages_media_split_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "expertise_pages_media_split" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_expertise_pages_media_split_visual_type" USING "visual_type"::"public"."enum_expertise_pages_media_split_visual_type";
  ALTER TABLE "expertise_pages_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_expertise_pages_split_narrow_visual_type";
  CREATE TYPE "public"."enum_expertise_pages_split_narrow_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "expertise_pages_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_expertise_pages_split_narrow_visual_type" USING "visual_type"::"public"."enum_expertise_pages_split_narrow_visual_type";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_expertise_pages_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum_expertise_pages_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_expertise_pages_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum_expertise_pages_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "__expertise_pages_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___expertise_pages_v_full_media_v_visual_type";
  CREATE TYPE "public"."enum___expertise_pages_v_full_media_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__expertise_pages_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___expertise_pages_v_full_media_v_visual_type" USING "visual_type"::"public"."enum___expertise_pages_v_full_media_v_visual_type";
  ALTER TABLE "__expertise_pages_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___expertise_pages_v_media_split_v_visual_type";
  CREATE TYPE "public"."enum___expertise_pages_v_media_split_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__expertise_pages_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___expertise_pages_v_media_split_v_visual_type" USING "visual_type"::"public"."enum___expertise_pages_v_media_split_v_visual_type";
  ALTER TABLE "__expertise_pages_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___expertise_pages_v_split_narrow_v_visual_type";
  CREATE TYPE "public"."enum___expertise_pages_v_split_narrow_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__expertise_pages_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___expertise_pages_v_split_narrow_v_visual_type" USING "visual_type"::"public"."enum___expertise_pages_v_split_narrow_v_visual_type";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__expertise_pages_v_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum__expertise_pages_v_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum__expertise_pages_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "audience_pages_full_media" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_audience_pages_full_media_visual_type";
  CREATE TYPE "public"."enum_audience_pages_full_media_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "audience_pages_full_media" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_audience_pages_full_media_visual_type" USING "visual_type"::"public"."enum_audience_pages_full_media_visual_type";
  ALTER TABLE "audience_pages_media_split" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_audience_pages_media_split_visual_type";
  CREATE TYPE "public"."enum_audience_pages_media_split_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "audience_pages_media_split" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_audience_pages_media_split_visual_type" USING "visual_type"::"public"."enum_audience_pages_media_split_visual_type";
  ALTER TABLE "audience_pages_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_audience_pages_split_narrow_visual_type";
  CREATE TYPE "public"."enum_audience_pages_split_narrow_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "audience_pages_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_audience_pages_split_narrow_visual_type" USING "visual_type"::"public"."enum_audience_pages_split_narrow_visual_type";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_audience_pages_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum_audience_pages_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_audience_pages_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum_audience_pages_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "__audience_pages_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___audience_pages_v_full_media_v_visual_type";
  CREATE TYPE "public"."enum___audience_pages_v_full_media_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__audience_pages_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___audience_pages_v_full_media_v_visual_type" USING "visual_type"::"public"."enum___audience_pages_v_full_media_v_visual_type";
  ALTER TABLE "__audience_pages_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___audience_pages_v_media_split_v_visual_type";
  CREATE TYPE "public"."enum___audience_pages_v_media_split_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__audience_pages_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___audience_pages_v_media_split_v_visual_type" USING "visual_type"::"public"."enum___audience_pages_v_media_split_v_visual_type";
  ALTER TABLE "__audience_pages_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___audience_pages_v_split_narrow_v_visual_type";
  CREATE TYPE "public"."enum___audience_pages_v_split_narrow_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__audience_pages_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___audience_pages_v_split_narrow_v_visual_type" USING "visual_type"::"public"."enum___audience_pages_v_split_narrow_v_visual_type";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__audience_pages_v_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum__audience_pages_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum__audience_pages_v_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum__audience_pages_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "home_full_media" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_home_full_media_visual_type";
  CREATE TYPE "public"."enum_home_full_media_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "home_full_media" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_home_full_media_visual_type" USING "visual_type"::"public"."enum_home_full_media_visual_type";
  ALTER TABLE "home_media_split" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_home_media_split_visual_type";
  CREATE TYPE "public"."enum_home_media_split_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "home_media_split" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_home_media_split_visual_type" USING "visual_type"::"public"."enum_home_media_split_visual_type";
  ALTER TABLE "home_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_home_split_narrow_visual_type";
  CREATE TYPE "public"."enum_home_split_narrow_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "home_split_narrow" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_home_split_narrow_visual_type" USING "visual_type"::"public"."enum_home_split_narrow_visual_type";
  ALTER TABLE "home_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_home_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum_home_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "home_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum_home_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum_home_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "__home_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___home_v_full_media_v_visual_type";
  CREATE TYPE "public"."enum___home_v_full_media_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__home_v_full_media_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___home_v_full_media_v_visual_type" USING "visual_type"::"public"."enum___home_v_full_media_v_visual_type";
  ALTER TABLE "__home_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___home_v_media_split_v_visual_type";
  CREATE TYPE "public"."enum___home_v_media_split_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__home_v_media_split_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___home_v_media_split_v_visual_type" USING "visual_type"::"public"."enum___home_v_media_split_v_visual_type";
  ALTER TABLE "__home_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum___home_v_split_narrow_v_visual_type";
  CREATE TYPE "public"."enum___home_v_split_narrow_v_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "__home_v_split_narrow_v" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum___home_v_split_narrow_v_visual_type" USING "visual_type"::"public"."enum___home_v_split_narrow_v_visual_type";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__home_v_blocks_feature_tabs_tabs_visual_type";
  CREATE TYPE "public"."enum__home_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ALTER COLUMN "visual_type" SET DATA TYPE "public"."enum__home_v_blocks_feature_tabs_tabs_visual_type" USING "visual_type"::"public"."enum__home_v_blocks_feature_tabs_tabs_visual_type";
  DROP INDEX "streak_looks_effect_idx";
  DROP INDEX "_streak_looks_v_version_version_effect_idx";
  ALTER TABLE "pages_full_media" DROP COLUMN "shader_bleed";
  ALTER TABLE "pages_full_media" DROP COLUMN "shader_origin";
  ALTER TABLE "pages_full_media" DROP COLUMN "shader_show_media";
  ALTER TABLE "pages_media_split" DROP COLUMN "shader_bleed";
  ALTER TABLE "pages_media_split" DROP COLUMN "shader_origin";
  ALTER TABLE "pages_media_split" DROP COLUMN "shader_show_media";
  ALTER TABLE "pages_split_narrow" DROP COLUMN "shader_bleed";
  ALTER TABLE "pages_split_narrow" DROP COLUMN "shader_origin";
  ALTER TABLE "pages_split_narrow" DROP COLUMN "shader_show_media";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "__pages_v_full_media_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__pages_v_full_media_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__pages_v_full_media_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__pages_v_media_split_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__pages_v_media_split_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__pages_v_media_split_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__pages_v_split_narrow_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__pages_v_split_narrow_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__pages_v_split_narrow_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "posts_full_media" DROP COLUMN "shader_bleed";
  ALTER TABLE "posts_full_media" DROP COLUMN "shader_origin";
  ALTER TABLE "posts_full_media" DROP COLUMN "shader_show_media";
  ALTER TABLE "posts_media_split" DROP COLUMN "shader_bleed";
  ALTER TABLE "posts_media_split" DROP COLUMN "shader_origin";
  ALTER TABLE "posts_media_split" DROP COLUMN "shader_show_media";
  ALTER TABLE "posts_split_narrow" DROP COLUMN "shader_bleed";
  ALTER TABLE "posts_split_narrow" DROP COLUMN "shader_origin";
  ALTER TABLE "posts_split_narrow" DROP COLUMN "shader_show_media";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "__posts_v_full_media_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__posts_v_full_media_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__posts_v_full_media_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__posts_v_media_split_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__posts_v_media_split_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__posts_v_media_split_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__posts_v_split_narrow_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__posts_v_split_narrow_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__posts_v_split_narrow_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "work_pages_full_media" DROP COLUMN "shader_bleed";
  ALTER TABLE "work_pages_full_media" DROP COLUMN "shader_origin";
  ALTER TABLE "work_pages_full_media" DROP COLUMN "shader_show_media";
  ALTER TABLE "work_pages_media_split" DROP COLUMN "shader_bleed";
  ALTER TABLE "work_pages_media_split" DROP COLUMN "shader_origin";
  ALTER TABLE "work_pages_media_split" DROP COLUMN "shader_show_media";
  ALTER TABLE "work_pages_split_narrow" DROP COLUMN "shader_bleed";
  ALTER TABLE "work_pages_split_narrow" DROP COLUMN "shader_origin";
  ALTER TABLE "work_pages_split_narrow" DROP COLUMN "shader_show_media";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "__work_pages_v_full_media_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__work_pages_v_full_media_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__work_pages_v_full_media_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__work_pages_v_media_split_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__work_pages_v_media_split_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__work_pages_v_media_split_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__work_pages_v_split_narrow_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__work_pages_v_split_narrow_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__work_pages_v_split_narrow_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "lab_pages_full_media" DROP COLUMN "shader_bleed";
  ALTER TABLE "lab_pages_full_media" DROP COLUMN "shader_origin";
  ALTER TABLE "lab_pages_full_media" DROP COLUMN "shader_show_media";
  ALTER TABLE "lab_pages_media_split" DROP COLUMN "shader_bleed";
  ALTER TABLE "lab_pages_media_split" DROP COLUMN "shader_origin";
  ALTER TABLE "lab_pages_media_split" DROP COLUMN "shader_show_media";
  ALTER TABLE "lab_pages_split_narrow" DROP COLUMN "shader_bleed";
  ALTER TABLE "lab_pages_split_narrow" DROP COLUMN "shader_origin";
  ALTER TABLE "lab_pages_split_narrow" DROP COLUMN "shader_show_media";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "__lab_pages_v_full_media_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__lab_pages_v_full_media_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__lab_pages_v_full_media_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__lab_pages_v_media_split_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__lab_pages_v_media_split_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__lab_pages_v_media_split_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__lab_pages_v_split_narrow_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__lab_pages_v_split_narrow_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__lab_pages_v_split_narrow_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "expertise_pages_full_media" DROP COLUMN "shader_bleed";
  ALTER TABLE "expertise_pages_full_media" DROP COLUMN "shader_origin";
  ALTER TABLE "expertise_pages_full_media" DROP COLUMN "shader_show_media";
  ALTER TABLE "expertise_pages_media_split" DROP COLUMN "shader_bleed";
  ALTER TABLE "expertise_pages_media_split" DROP COLUMN "shader_origin";
  ALTER TABLE "expertise_pages_media_split" DROP COLUMN "shader_show_media";
  ALTER TABLE "expertise_pages_split_narrow" DROP COLUMN "shader_bleed";
  ALTER TABLE "expertise_pages_split_narrow" DROP COLUMN "shader_origin";
  ALTER TABLE "expertise_pages_split_narrow" DROP COLUMN "shader_show_media";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "__expertise_pages_v_full_media_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__expertise_pages_v_full_media_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__expertise_pages_v_full_media_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__expertise_pages_v_media_split_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__expertise_pages_v_media_split_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__expertise_pages_v_media_split_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__expertise_pages_v_split_narrow_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__expertise_pages_v_split_narrow_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__expertise_pages_v_split_narrow_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "audience_pages_full_media" DROP COLUMN "shader_bleed";
  ALTER TABLE "audience_pages_full_media" DROP COLUMN "shader_origin";
  ALTER TABLE "audience_pages_full_media" DROP COLUMN "shader_show_media";
  ALTER TABLE "audience_pages_media_split" DROP COLUMN "shader_bleed";
  ALTER TABLE "audience_pages_media_split" DROP COLUMN "shader_origin";
  ALTER TABLE "audience_pages_media_split" DROP COLUMN "shader_show_media";
  ALTER TABLE "audience_pages_split_narrow" DROP COLUMN "shader_bleed";
  ALTER TABLE "audience_pages_split_narrow" DROP COLUMN "shader_origin";
  ALTER TABLE "audience_pages_split_narrow" DROP COLUMN "shader_show_media";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "__audience_pages_v_full_media_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__audience_pages_v_full_media_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__audience_pages_v_full_media_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__audience_pages_v_media_split_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__audience_pages_v_media_split_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__audience_pages_v_media_split_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__audience_pages_v_split_narrow_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__audience_pages_v_split_narrow_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__audience_pages_v_split_narrow_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "streak_looks" DROP COLUMN "effect";
  ALTER TABLE "_streak_looks_v" DROP COLUMN "version_effect";
  ALTER TABLE "home_full_media" DROP COLUMN "shader_bleed";
  ALTER TABLE "home_full_media" DROP COLUMN "shader_origin";
  ALTER TABLE "home_full_media" DROP COLUMN "shader_show_media";
  ALTER TABLE "home_media_split" DROP COLUMN "shader_bleed";
  ALTER TABLE "home_media_split" DROP COLUMN "shader_origin";
  ALTER TABLE "home_media_split" DROP COLUMN "shader_show_media";
  ALTER TABLE "home_split_narrow" DROP COLUMN "shader_bleed";
  ALTER TABLE "home_split_narrow" DROP COLUMN "shader_origin";
  ALTER TABLE "home_split_narrow" DROP COLUMN "shader_show_media";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  ALTER TABLE "__home_v_full_media_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__home_v_full_media_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__home_v_full_media_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__home_v_media_split_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__home_v_media_split_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__home_v_media_split_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "__home_v_split_narrow_v" DROP COLUMN "shader_bleed";
  ALTER TABLE "__home_v_split_narrow_v" DROP COLUMN "shader_origin";
  ALTER TABLE "__home_v_split_narrow_v" DROP COLUMN "shader_show_media";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_bleed";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_origin";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_show_media";
  DROP TYPE "public"."enum_pages_full_media_shader_origin";
  DROP TYPE "public"."enum_pages_media_split_shader_origin";
  DROP TYPE "public"."enum_pages_split_narrow_shader_origin";
  DROP TYPE "public"."enum_pages_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum___pages_v_full_media_v_shader_origin";
  DROP TYPE "public"."enum___pages_v_media_split_v_shader_origin";
  DROP TYPE "public"."enum___pages_v_split_narrow_v_shader_origin";
  DROP TYPE "public"."enum__pages_v_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum_posts_full_media_shader_origin";
  DROP TYPE "public"."enum_posts_media_split_shader_origin";
  DROP TYPE "public"."enum_posts_split_narrow_shader_origin";
  DROP TYPE "public"."enum_posts_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum___posts_v_full_media_v_shader_origin";
  DROP TYPE "public"."enum___posts_v_media_split_v_shader_origin";
  DROP TYPE "public"."enum___posts_v_split_narrow_v_shader_origin";
  DROP TYPE "public"."enum__posts_v_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum_work_pages_full_media_shader_origin";
  DROP TYPE "public"."enum_work_pages_media_split_shader_origin";
  DROP TYPE "public"."enum_work_pages_split_narrow_shader_origin";
  DROP TYPE "public"."enum_work_pages_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum___work_pages_v_full_media_v_shader_origin";
  DROP TYPE "public"."enum___work_pages_v_media_split_v_shader_origin";
  DROP TYPE "public"."enum___work_pages_v_split_narrow_v_shader_origin";
  DROP TYPE "public"."enum__work_pages_v_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum_lab_pages_full_media_shader_origin";
  DROP TYPE "public"."enum_lab_pages_media_split_shader_origin";
  DROP TYPE "public"."enum_lab_pages_split_narrow_shader_origin";
  DROP TYPE "public"."enum_lab_pages_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum___lab_pages_v_full_media_v_shader_origin";
  DROP TYPE "public"."enum___lab_pages_v_media_split_v_shader_origin";
  DROP TYPE "public"."enum___lab_pages_v_split_narrow_v_shader_origin";
  DROP TYPE "public"."enum__lab_pages_v_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum_expertise_pages_full_media_shader_origin";
  DROP TYPE "public"."enum_expertise_pages_media_split_shader_origin";
  DROP TYPE "public"."enum_expertise_pages_split_narrow_shader_origin";
  DROP TYPE "public"."enum_expertise_pages_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum___expertise_pages_v_full_media_v_shader_origin";
  DROP TYPE "public"."enum___expertise_pages_v_media_split_v_shader_origin";
  DROP TYPE "public"."enum___expertise_pages_v_split_narrow_v_shader_origin";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum_audience_pages_full_media_shader_origin";
  DROP TYPE "public"."enum_audience_pages_media_split_shader_origin";
  DROP TYPE "public"."enum_audience_pages_split_narrow_shader_origin";
  DROP TYPE "public"."enum_audience_pages_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum___audience_pages_v_full_media_v_shader_origin";
  DROP TYPE "public"."enum___audience_pages_v_media_split_v_shader_origin";
  DROP TYPE "public"."enum___audience_pages_v_split_narrow_v_shader_origin";
  DROP TYPE "public"."enum__audience_pages_v_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum_streak_looks_effect";
  DROP TYPE "public"."enum__streak_looks_v_version_effect";
  DROP TYPE "public"."enum_home_full_media_shader_origin";
  DROP TYPE "public"."enum_home_media_split_shader_origin";
  DROP TYPE "public"."enum_home_split_narrow_shader_origin";
  DROP TYPE "public"."enum_home_blocks_feature_tabs_tabs_shader_origin";
  DROP TYPE "public"."enum___home_v_full_media_v_shader_origin";
  DROP TYPE "public"."enum___home_v_media_split_v_shader_origin";
  DROP TYPE "public"."enum___home_v_split_narrow_v_shader_origin";
  DROP TYPE "public"."enum__home_v_blocks_feature_tabs_tabs_shader_origin";`)
}
