import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_pages_aud_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum__pages_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum___pages_v_aud_tabs_v_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_posts_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum__posts_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_work_pages_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_work_pages_aud_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum__work_pages_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum___work_pages_v_aud_tabs_v_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_lab_pages_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum__lab_pages_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_expertise_pages_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_expertise_pages_aud_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum___expertise_pages_v_aud_tabs_v_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_audience_pages_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_audience_pages_aud_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum___audience_pages_v_aud_tabs_v_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_home_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum_home_aud_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum__home_v_blocks_feature_tabs_tabs_visual_type" AS ENUM('media', 'streakField');
  CREATE TYPE "public"."enum___home_v_aud_tabs_v_tabs_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum_pages_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "pages_aud_tabs_tabs" ADD COLUMN "visual_type" "enum_pages_aud_tabs_tabs_visual_type";
  ALTER TABLE "pages_aud_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "pages_aud_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "pages_aud_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "pages_aud_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "pages_aud_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "pages_aud_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum__pages_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" ADD COLUMN "visual_type" "enum___pages_v_aud_tabs_v_tabs_visual_type";
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum_posts_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum__posts_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum_work_pages_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "work_pages_aud_tabs_tabs" ADD COLUMN "visual_type" "enum_work_pages_aud_tabs_tabs_visual_type";
  ALTER TABLE "work_pages_aud_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "work_pages_aud_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "work_pages_aud_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "work_pages_aud_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "work_pages_aud_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "work_pages_aud_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum__work_pages_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" ADD COLUMN "visual_type" "enum___work_pages_v_aud_tabs_v_tabs_visual_type";
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum_lab_pages_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum__lab_pages_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum_expertise_pages_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "expertise_pages_aud_tabs_tabs" ADD COLUMN "visual_type" "enum_expertise_pages_aud_tabs_tabs_visual_type";
  ALTER TABLE "expertise_pages_aud_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "expertise_pages_aud_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "expertise_pages_aud_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "expertise_pages_aud_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "expertise_pages_aud_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_aud_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum__expertise_pages_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" ADD COLUMN "visual_type" "enum___expertise_pages_v_aud_tabs_v_tabs_visual_type";
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum_audience_pages_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "audience_pages_aud_tabs_tabs" ADD COLUMN "visual_type" "enum_audience_pages_aud_tabs_tabs_visual_type";
  ALTER TABLE "audience_pages_aud_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "audience_pages_aud_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "audience_pages_aud_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "audience_pages_aud_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "audience_pages_aud_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "audience_pages_aud_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum__audience_pages_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" ADD COLUMN "visual_type" "enum___audience_pages_v_aud_tabs_v_tabs_visual_type";
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum_home_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "home_aud_tabs_tabs" ADD COLUMN "visual_type" "enum_home_aud_tabs_tabs_visual_type";
  ALTER TABLE "home_aud_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "home_aud_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "home_aud_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "home_aud_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "home_aud_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "home_aud_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "visual_type" "enum__home_v_blocks_feature_tabs_tabs_visual_type";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "__home_v_aud_tabs_v_tabs" ADD COLUMN "visual_type" "enum___home_v_aud_tabs_v_tabs_visual_type";
  ALTER TABLE "__home_v_aud_tabs_v_tabs" ADD COLUMN "shader_preset" varchar;
  ALTER TABLE "__home_v_aud_tabs_v_tabs" ADD COLUMN "shader_seed" numeric;
  ALTER TABLE "__home_v_aud_tabs_v_tabs" ADD COLUMN "shader_speed" numeric;
  ALTER TABLE "__home_v_aud_tabs_v_tabs" ADD COLUMN "shader_intensity" numeric;
  ALTER TABLE "__home_v_aud_tabs_v_tabs" ADD COLUMN "shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "__home_v_aud_tabs_v_tabs" ADD COLUMN "shader_poster_media_id" integer;
  ALTER TABLE "pages_blocks_feature_tabs_tabs" ADD CONSTRAINT "pages_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_aud_tabs_tabs" ADD CONSTRAINT "pages_aud_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" ADD CONSTRAINT "_pages_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" ADD CONSTRAINT "__pages_v_aud_tabs_v_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "posts_blocks_feature_tabs_tabs" ADD CONSTRAINT "posts_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" ADD CONSTRAINT "_posts_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" ADD CONSTRAINT "work_pages_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "work_pages_aud_tabs_tabs" ADD CONSTRAINT "work_pages_aud_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" ADD CONSTRAINT "_work_pages_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" ADD CONSTRAINT "__work_pages_v_aud_tabs_v_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" ADD CONSTRAINT "lab_pages_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" ADD CONSTRAINT "_lab_pages_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" ADD CONSTRAINT "expertise_pages_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expertise_pages_aud_tabs_tabs" ADD CONSTRAINT "expertise_pages_aud_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" ADD CONSTRAINT "_expertise_pages_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" ADD CONSTRAINT "__expertise_pages_v_aud_tabs_v_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" ADD CONSTRAINT "audience_pages_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "audience_pages_aud_tabs_tabs" ADD CONSTRAINT "audience_pages_aud_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" ADD CONSTRAINT "_audience_pages_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" ADD CONSTRAINT "__audience_pages_v_aud_tabs_v_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "home_blocks_feature_tabs_tabs" ADD CONSTRAINT "home_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "home_aud_tabs_tabs" ADD CONSTRAINT "home_aud_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" ADD CONSTRAINT "_home_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "__home_v_aud_tabs_v_tabs" ADD CONSTRAINT "__home_v_aud_tabs_v_tabs_shader_poster_media_id_media_id_fk" FOREIGN KEY ("shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "pages_blocks_feature_tabs_tabs_shader_shader_poster_medi_idx" ON "pages_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "pages_aud_tabs_tabs_shader_shader_poster_media_idx" ON "pages_aud_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "_pages_v_blocks_feature_tabs_tabs_shader_shader_poster_m_idx" ON "_pages_v_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "__pages_v_aud_tabs_v_tabs_shader_shader_poster_media_idx" ON "__pages_v_aud_tabs_v_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "posts_blocks_feature_tabs_tabs_shader_shader_poster_medi_idx" ON "posts_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "_posts_v_blocks_feature_tabs_tabs_shader_shader_poster_m_idx" ON "_posts_v_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "work_pages_blocks_feature_tabs_tabs_shader_shader_poster_idx" ON "work_pages_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "work_pages_aud_tabs_tabs_shader_shader_poster_media_idx" ON "work_pages_aud_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "_work_pages_v_blocks_feature_tabs_tabs_shader_shader_pos_idx" ON "_work_pages_v_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "__work_pages_v_aud_tabs_v_tabs_shader_shader_poster_medi_idx" ON "__work_pages_v_aud_tabs_v_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "lab_pages_blocks_feature_tabs_tabs_shader_shader_poster__idx" ON "lab_pages_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "_lab_pages_v_blocks_feature_tabs_tabs_shader_shader_post_idx" ON "_lab_pages_v_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "expertise_pages_blocks_feature_tabs_tabs_shader_shader_p_idx" ON "expertise_pages_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "expertise_pages_aud_tabs_tabs_shader_shader_poster_media_idx" ON "expertise_pages_aud_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "_expertise_pages_v_blocks_feature_tabs_tabs_shader_shade_idx" ON "_expertise_pages_v_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "__expertise_pages_v_aud_tabs_v_tabs_shader_shader_poster_idx" ON "__expertise_pages_v_aud_tabs_v_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "audience_pages_blocks_feature_tabs_tabs_shader_shader_po_idx" ON "audience_pages_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "audience_pages_aud_tabs_tabs_shader_shader_poster_media_idx" ON "audience_pages_aud_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "_audience_pages_v_blocks_feature_tabs_tabs_shader_shader_idx" ON "_audience_pages_v_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "__audience_pages_v_aud_tabs_v_tabs_shader_shader_poster__idx" ON "__audience_pages_v_aud_tabs_v_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "home_blocks_feature_tabs_tabs_shader_shader_poster_media_idx" ON "home_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "home_aud_tabs_tabs_shader_shader_poster_media_idx" ON "home_aud_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "_home_v_blocks_feature_tabs_tabs_shader_shader_poster_me_idx" ON "_home_v_blocks_feature_tabs_tabs" USING btree ("shader_poster_media_id");
  CREATE INDEX "__home_v_aud_tabs_v_tabs_shader_shader_poster_media_idx" ON "__home_v_aud_tabs_v_tabs" USING btree ("shader_poster_media_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP CONSTRAINT "pages_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "pages_aud_tabs_tabs" DROP CONSTRAINT "pages_aud_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP CONSTRAINT "_pages_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" DROP CONSTRAINT "__pages_v_aud_tabs_v_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP CONSTRAINT "posts_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP CONSTRAINT "_posts_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP CONSTRAINT "work_pages_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "work_pages_aud_tabs_tabs" DROP CONSTRAINT "work_pages_aud_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP CONSTRAINT "_work_pages_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" DROP CONSTRAINT "__work_pages_v_aud_tabs_v_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP CONSTRAINT "lab_pages_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP CONSTRAINT "_lab_pages_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP CONSTRAINT "expertise_pages_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "expertise_pages_aud_tabs_tabs" DROP CONSTRAINT "expertise_pages_aud_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP CONSTRAINT "_expertise_pages_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" DROP CONSTRAINT "__expertise_pages_v_aud_tabs_v_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP CONSTRAINT "audience_pages_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "audience_pages_aud_tabs_tabs" DROP CONSTRAINT "audience_pages_aud_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP CONSTRAINT "_audience_pages_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" DROP CONSTRAINT "__audience_pages_v_aud_tabs_v_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP CONSTRAINT "home_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "home_aud_tabs_tabs" DROP CONSTRAINT "home_aud_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP CONSTRAINT "_home_v_blocks_feature_tabs_tabs_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "__home_v_aud_tabs_v_tabs" DROP CONSTRAINT "__home_v_aud_tabs_v_tabs_shader_poster_media_id_media_id_fk";
  
  DROP INDEX "pages_blocks_feature_tabs_tabs_shader_shader_poster_medi_idx";
  DROP INDEX "pages_aud_tabs_tabs_shader_shader_poster_media_idx";
  DROP INDEX "_pages_v_blocks_feature_tabs_tabs_shader_shader_poster_m_idx";
  DROP INDEX "__pages_v_aud_tabs_v_tabs_shader_shader_poster_media_idx";
  DROP INDEX "posts_blocks_feature_tabs_tabs_shader_shader_poster_medi_idx";
  DROP INDEX "_posts_v_blocks_feature_tabs_tabs_shader_shader_poster_m_idx";
  DROP INDEX "work_pages_blocks_feature_tabs_tabs_shader_shader_poster_idx";
  DROP INDEX "work_pages_aud_tabs_tabs_shader_shader_poster_media_idx";
  DROP INDEX "_work_pages_v_blocks_feature_tabs_tabs_shader_shader_pos_idx";
  DROP INDEX "__work_pages_v_aud_tabs_v_tabs_shader_shader_poster_medi_idx";
  DROP INDEX "lab_pages_blocks_feature_tabs_tabs_shader_shader_poster__idx";
  DROP INDEX "_lab_pages_v_blocks_feature_tabs_tabs_shader_shader_post_idx";
  DROP INDEX "expertise_pages_blocks_feature_tabs_tabs_shader_shader_p_idx";
  DROP INDEX "expertise_pages_aud_tabs_tabs_shader_shader_poster_media_idx";
  DROP INDEX "_expertise_pages_v_blocks_feature_tabs_tabs_shader_shade_idx";
  DROP INDEX "__expertise_pages_v_aud_tabs_v_tabs_shader_shader_poster_idx";
  DROP INDEX "audience_pages_blocks_feature_tabs_tabs_shader_shader_po_idx";
  DROP INDEX "audience_pages_aud_tabs_tabs_shader_shader_poster_media_idx";
  DROP INDEX "_audience_pages_v_blocks_feature_tabs_tabs_shader_shader_idx";
  DROP INDEX "__audience_pages_v_aud_tabs_v_tabs_shader_shader_poster__idx";
  DROP INDEX "home_blocks_feature_tabs_tabs_shader_shader_poster_media_idx";
  DROP INDEX "home_aud_tabs_tabs_shader_shader_poster_media_idx";
  DROP INDEX "_home_v_blocks_feature_tabs_tabs_shader_shader_poster_me_idx";
  DROP INDEX "__home_v_aud_tabs_v_tabs_shader_shader_poster_media_idx";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "pages_aud_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "pages_aud_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "pages_aud_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "pages_aud_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "pages_aud_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "pages_aud_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "pages_aud_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "__pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "posts_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "_posts_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "work_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "work_pages_aud_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "work_pages_aud_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "work_pages_aud_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "work_pages_aud_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "work_pages_aud_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "work_pages_aud_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "work_pages_aud_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "__work_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "lab_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "expertise_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "expertise_pages_aud_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "expertise_pages_aud_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "expertise_pages_aud_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "expertise_pages_aud_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "expertise_pages_aud_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "expertise_pages_aud_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "expertise_pages_aud_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "__expertise_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "audience_pages_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "audience_pages_aud_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "audience_pages_aud_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "audience_pages_aud_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "audience_pages_aud_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "audience_pages_aud_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "audience_pages_aud_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "audience_pages_aud_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "__audience_pages_v_aud_tabs_v_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "home_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "home_aud_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "home_aud_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "home_aud_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "home_aud_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "home_aud_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "home_aud_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "home_aud_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "_home_v_blocks_feature_tabs_tabs" DROP COLUMN "shader_poster_media_id";
  ALTER TABLE "__home_v_aud_tabs_v_tabs" DROP COLUMN "visual_type";
  ALTER TABLE "__home_v_aud_tabs_v_tabs" DROP COLUMN "shader_preset";
  ALTER TABLE "__home_v_aud_tabs_v_tabs" DROP COLUMN "shader_seed";
  ALTER TABLE "__home_v_aud_tabs_v_tabs" DROP COLUMN "shader_speed";
  ALTER TABLE "__home_v_aud_tabs_v_tabs" DROP COLUMN "shader_intensity";
  ALTER TABLE "__home_v_aud_tabs_v_tabs" DROP COLUMN "shader_pointer_interaction";
  ALTER TABLE "__home_v_aud_tabs_v_tabs" DROP COLUMN "shader_poster_media_id";
  DROP TYPE "public"."enum_pages_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum_pages_aud_tabs_tabs_visual_type";
  DROP TYPE "public"."enum__pages_v_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum___pages_v_aud_tabs_v_tabs_visual_type";
  DROP TYPE "public"."enum_posts_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum__posts_v_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum_work_pages_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum_work_pages_aud_tabs_tabs_visual_type";
  DROP TYPE "public"."enum__work_pages_v_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum___work_pages_v_aud_tabs_v_tabs_visual_type";
  DROP TYPE "public"."enum_lab_pages_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum__lab_pages_v_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum_expertise_pages_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum_expertise_pages_aud_tabs_tabs_visual_type";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum___expertise_pages_v_aud_tabs_v_tabs_visual_type";
  DROP TYPE "public"."enum_audience_pages_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum_audience_pages_aud_tabs_tabs_visual_type";
  DROP TYPE "public"."enum__audience_pages_v_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum___audience_pages_v_aud_tabs_v_tabs_visual_type";
  DROP TYPE "public"."enum_home_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum_home_aud_tabs_tabs_visual_type";
  DROP TYPE "public"."enum__home_v_blocks_feature_tabs_tabs_visual_type";
  DROP TYPE "public"."enum___home_v_aud_tabs_v_tabs_visual_type";`)
}
