import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_hero_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_pages_blocks_content_columns_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_pages_stmt_links_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_pages_blocks_testimonials_marquee_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_pages_blocks_cta_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__pages_v_version_hero_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum___pages_v_stmt_links_v_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_marquee_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_work_pages_stmt_links_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum___work_pages_v_stmt_links_v_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_expertise_pages_hero_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_expertise_pages_blocks_content_columns_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_expertise_pages_blocks_cta_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__expertise_pages_v_version_hero_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_content_columns_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_cta_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_audience_pages_hero_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_audience_pages_blocks_content_columns_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_audience_pages_blocks_cta_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__audience_pages_v_version_hero_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_content_columns_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_cta_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_home_blocks_content_columns_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_home_stmt_links_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_home_blocks_testimonials_marquee_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_home_blocks_cta_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__home_v_blocks_content_columns_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum___home_v_stmt_links_v_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__home_v_blocks_testimonials_marquee_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__home_v_blocks_cta_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_insights_index_hero_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__insights_index_v_version_hero_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_works_index_hero_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum__works_index_v_version_hero_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_header_nav_items_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_footer_closing_links_link_site_page" AS ENUM('home', 'works-index', 'insights-index');
  CREATE TYPE "public"."enum_footer_get_in_touch_site_page" AS ENUM('home', 'works-index', 'insights-index');
  ALTER TYPE "public"."enum_pages_hero_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_pages_blocks_content_columns_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_pages_stmt_links_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_pages_blocks_testimonials_marquee_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_pages_blocks_cta_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__pages_v_version_hero_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__pages_v_blocks_content_columns_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum___pages_v_stmt_links_v_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__pages_v_blocks_testimonials_marquee_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__pages_v_blocks_cta_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_work_pages_stmt_links_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum___work_pages_v_stmt_links_v_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_expertise_pages_hero_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_expertise_pages_blocks_content_columns_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_expertise_pages_blocks_cta_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__expertise_pages_v_version_hero_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__expertise_pages_v_blocks_content_columns_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__expertise_pages_v_blocks_cta_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_audience_pages_hero_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_audience_pages_blocks_content_columns_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_audience_pages_blocks_cta_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__audience_pages_v_version_hero_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__audience_pages_v_blocks_content_columns_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__audience_pages_v_blocks_cta_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_home_blocks_content_columns_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_home_stmt_links_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_home_blocks_testimonials_marquee_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_home_blocks_cta_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__home_v_blocks_content_columns_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum___home_v_stmt_links_v_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__home_v_blocks_testimonials_marquee_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__home_v_blocks_cta_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_insights_index_hero_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__insights_index_v_version_hero_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_works_index_hero_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum__works_index_v_version_hero_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_header_nav_items_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_footer_closing_links_link_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TYPE "public"."enum_footer_get_in_touch_type" ADD VALUE 'site' BEFORE 'custom';
  ALTER TABLE "pages_hero_links" ADD COLUMN "link_site_page" "enum_pages_hero_links_link_site_page";
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "link_site_page" "enum_pages_blocks_content_columns_link_site_page";
  ALTER TABLE "pages_stmt_links_links" ADD COLUMN "link_site_page" "enum_pages_stmt_links_links_link_site_page";
  ALTER TABLE "pages_blocks_testimonials_marquee_links" ADD COLUMN "link_site_page" "enum_pages_blocks_testimonials_marquee_links_link_site_page";
  ALTER TABLE "pages_blocks_cta_links" ADD COLUMN "link_site_page" "enum_pages_blocks_cta_links_link_site_page";
  ALTER TABLE "_pages_v_version_hero_links" ADD COLUMN "link_site_page" "enum__pages_v_version_hero_links_link_site_page";
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "link_site_page" "enum__pages_v_blocks_content_columns_link_site_page";
  ALTER TABLE "__pages_v_stmt_links_v_links" ADD COLUMN "link_site_page" "enum___pages_v_stmt_links_v_links_link_site_page";
  ALTER TABLE "_pages_v_blocks_testimonials_marquee_links" ADD COLUMN "link_site_page" "enum__pages_v_blocks_testimonials_marquee_links_link_site_page";
  ALTER TABLE "_pages_v_blocks_cta_links" ADD COLUMN "link_site_page" "enum__pages_v_blocks_cta_links_link_site_page";
  ALTER TABLE "work_pages_stmt_links_links" ADD COLUMN "link_site_page" "enum_work_pages_stmt_links_links_link_site_page";
  ALTER TABLE "__work_pages_v_stmt_links_v_links" ADD COLUMN "link_site_page" "enum___work_pages_v_stmt_links_v_links_link_site_page";
  ALTER TABLE "expertise_pages_hero_links" ADD COLUMN "link_site_page" "enum_expertise_pages_hero_links_link_site_page";
  ALTER TABLE "expertise_pages_blocks_content_columns" ADD COLUMN "link_site_page" "enum_expertise_pages_blocks_content_columns_link_site_page";
  ALTER TABLE "expertise_pages_blocks_cta_links" ADD COLUMN "link_site_page" "enum_expertise_pages_blocks_cta_links_link_site_page";
  ALTER TABLE "_expertise_pages_v_version_hero_links" ADD COLUMN "link_site_page" "enum__expertise_pages_v_version_hero_links_link_site_page";
  ALTER TABLE "_expertise_pages_v_blocks_content_columns" ADD COLUMN "link_site_page" "enum__expertise_pages_v_blocks_content_columns_link_site_page";
  ALTER TABLE "_expertise_pages_v_blocks_cta_links" ADD COLUMN "link_site_page" "enum__expertise_pages_v_blocks_cta_links_link_site_page";
  ALTER TABLE "audience_pages_hero_links" ADD COLUMN "link_site_page" "enum_audience_pages_hero_links_link_site_page";
  ALTER TABLE "audience_pages_blocks_content_columns" ADD COLUMN "link_site_page" "enum_audience_pages_blocks_content_columns_link_site_page";
  ALTER TABLE "audience_pages_blocks_cta_links" ADD COLUMN "link_site_page" "enum_audience_pages_blocks_cta_links_link_site_page";
  ALTER TABLE "_audience_pages_v_version_hero_links" ADD COLUMN "link_site_page" "enum__audience_pages_v_version_hero_links_link_site_page";
  ALTER TABLE "_audience_pages_v_blocks_content_columns" ADD COLUMN "link_site_page" "enum__audience_pages_v_blocks_content_columns_link_site_page";
  ALTER TABLE "_audience_pages_v_blocks_cta_links" ADD COLUMN "link_site_page" "enum__audience_pages_v_blocks_cta_links_link_site_page";
  ALTER TABLE "home_blocks_content_columns" ADD COLUMN "link_site_page" "enum_home_blocks_content_columns_link_site_page";
  ALTER TABLE "home_stmt_links_links" ADD COLUMN "link_site_page" "enum_home_stmt_links_links_link_site_page";
  ALTER TABLE "home_blocks_testimonials_marquee_links" ADD COLUMN "link_site_page" "enum_home_blocks_testimonials_marquee_links_link_site_page";
  ALTER TABLE "home_blocks_cta_links" ADD COLUMN "link_site_page" "enum_home_blocks_cta_links_link_site_page";
  ALTER TABLE "_home_v_blocks_content_columns" ADD COLUMN "link_site_page" "enum__home_v_blocks_content_columns_link_site_page";
  ALTER TABLE "__home_v_stmt_links_v_links" ADD COLUMN "link_site_page" "enum___home_v_stmt_links_v_links_link_site_page";
  ALTER TABLE "_home_v_blocks_testimonials_marquee_links" ADD COLUMN "link_site_page" "enum__home_v_blocks_testimonials_marquee_links_link_site_page";
  ALTER TABLE "_home_v_blocks_cta_links" ADD COLUMN "link_site_page" "enum__home_v_blocks_cta_links_link_site_page";
  ALTER TABLE "insights_index_hero_links" ADD COLUMN "link_site_page" "enum_insights_index_hero_links_link_site_page";
  ALTER TABLE "_insights_index_v_version_hero_links" ADD COLUMN "link_site_page" "enum__insights_index_v_version_hero_links_link_site_page";
  ALTER TABLE "works_index_hero_links" ADD COLUMN "link_site_page" "enum_works_index_hero_links_link_site_page";
  ALTER TABLE "_works_index_v_version_hero_links" ADD COLUMN "link_site_page" "enum__works_index_v_version_hero_links_link_site_page";
  ALTER TABLE "header_nav_items" ADD COLUMN "link_site_page" "enum_header_nav_items_link_site_page";
  ALTER TABLE "footer_closing_links" ADD COLUMN "link_site_page" "enum_footer_closing_links_link_site_page";
  ALTER TABLE "footer" ADD COLUMN "get_in_touch_site_page" "enum_footer_get_in_touch_site_page";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_hero_links_link_type";
  CREATE TYPE "public"."enum_pages_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_hero_links_link_type";
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_hero_links_link_type" USING "link_type"::"public"."enum_pages_hero_links_link_type";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_content_columns_link_type";
  CREATE TYPE "public"."enum_pages_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_content_columns_link_type";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_blocks_content_columns_link_type" USING "link_type"::"public"."enum_pages_blocks_content_columns_link_type";
  ALTER TABLE "pages_stmt_links_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_stmt_links_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_stmt_links_links_link_type";
  CREATE TYPE "public"."enum_pages_stmt_links_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_stmt_links_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_stmt_links_links_link_type";
  ALTER TABLE "pages_stmt_links_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_stmt_links_links_link_type" USING "link_type"::"public"."enum_pages_stmt_links_links_link_type";
  ALTER TABLE "pages_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_testimonials_marquee_links_link_type";
  CREATE TYPE "public"."enum_pages_blocks_testimonials_marquee_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_testimonials_marquee_links_link_type";
  ALTER TABLE "pages_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_blocks_testimonials_marquee_links_link_type" USING "link_type"::"public"."enum_pages_blocks_testimonials_marquee_links_link_type";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum_pages_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_cta_links_link_type";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_blocks_cta_links_link_type" USING "link_type"::"public"."enum_pages_blocks_cta_links_link_type";
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_version_hero_links_link_type";
  CREATE TYPE "public"."enum__pages_v_version_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_version_hero_links_link_type";
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_version_hero_links_link_type" USING "link_type"::"public"."enum__pages_v_version_hero_links_link_type";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_content_columns_link_type";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_blocks_content_columns_link_type" USING "link_type"::"public"."enum__pages_v_blocks_content_columns_link_type";
  ALTER TABLE "__pages_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "__pages_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum___pages_v_stmt_links_v_links_link_type";
  CREATE TYPE "public"."enum___pages_v_stmt_links_v_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "__pages_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum___pages_v_stmt_links_v_links_link_type";
  ALTER TABLE "__pages_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum___pages_v_stmt_links_v_links_link_type" USING "link_type"::"public"."enum___pages_v_stmt_links_v_links_link_type";
  ALTER TABLE "_pages_v_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_marquee_links_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_marquee_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_testimonials_marquee_links_link_type";
  ALTER TABLE "_pages_v_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_blocks_testimonials_marquee_links_link_type" USING "link_type"::"public"."enum__pages_v_blocks_testimonials_marquee_links_link_type";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_cta_links_link_type";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_blocks_cta_links_link_type" USING "link_type"::"public"."enum__pages_v_blocks_cta_links_link_type";
  ALTER TABLE "work_pages_stmt_links_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "work_pages_stmt_links_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_work_pages_stmt_links_links_link_type";
  CREATE TYPE "public"."enum_work_pages_stmt_links_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "work_pages_stmt_links_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_work_pages_stmt_links_links_link_type";
  ALTER TABLE "work_pages_stmt_links_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_work_pages_stmt_links_links_link_type" USING "link_type"::"public"."enum_work_pages_stmt_links_links_link_type";
  ALTER TABLE "__work_pages_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "__work_pages_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum___work_pages_v_stmt_links_v_links_link_type";
  CREATE TYPE "public"."enum___work_pages_v_stmt_links_v_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "__work_pages_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum___work_pages_v_stmt_links_v_links_link_type";
  ALTER TABLE "__work_pages_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum___work_pages_v_stmt_links_v_links_link_type" USING "link_type"::"public"."enum___work_pages_v_stmt_links_v_links_link_type";
  ALTER TABLE "expertise_pages_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "expertise_pages_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_expertise_pages_hero_links_link_type";
  CREATE TYPE "public"."enum_expertise_pages_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "expertise_pages_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_expertise_pages_hero_links_link_type";
  ALTER TABLE "expertise_pages_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_expertise_pages_hero_links_link_type" USING "link_type"::"public"."enum_expertise_pages_hero_links_link_type";
  ALTER TABLE "expertise_pages_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "expertise_pages_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_expertise_pages_blocks_content_columns_link_type";
  CREATE TYPE "public"."enum_expertise_pages_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "expertise_pages_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_expertise_pages_blocks_content_columns_link_type";
  ALTER TABLE "expertise_pages_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_expertise_pages_blocks_content_columns_link_type" USING "link_type"::"public"."enum_expertise_pages_blocks_content_columns_link_type";
  ALTER TABLE "expertise_pages_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "expertise_pages_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_expertise_pages_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum_expertise_pages_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "expertise_pages_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_expertise_pages_blocks_cta_links_link_type";
  ALTER TABLE "expertise_pages_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_expertise_pages_blocks_cta_links_link_type" USING "link_type"::"public"."enum_expertise_pages_blocks_cta_links_link_type";
  ALTER TABLE "_expertise_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_expertise_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__expertise_pages_v_version_hero_links_link_type";
  CREATE TYPE "public"."enum__expertise_pages_v_version_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_expertise_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__expertise_pages_v_version_hero_links_link_type";
  ALTER TABLE "_expertise_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__expertise_pages_v_version_hero_links_link_type" USING "link_type"::"public"."enum__expertise_pages_v_version_hero_links_link_type";
  ALTER TABLE "_expertise_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_expertise_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__expertise_pages_v_blocks_content_columns_link_type";
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_expertise_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__expertise_pages_v_blocks_content_columns_link_type";
  ALTER TABLE "_expertise_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__expertise_pages_v_blocks_content_columns_link_type" USING "link_type"::"public"."enum__expertise_pages_v_blocks_content_columns_link_type";
  ALTER TABLE "_expertise_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_expertise_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__expertise_pages_v_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_expertise_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__expertise_pages_v_blocks_cta_links_link_type";
  ALTER TABLE "_expertise_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__expertise_pages_v_blocks_cta_links_link_type" USING "link_type"::"public"."enum__expertise_pages_v_blocks_cta_links_link_type";
  ALTER TABLE "audience_pages_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "audience_pages_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_audience_pages_hero_links_link_type";
  CREATE TYPE "public"."enum_audience_pages_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "audience_pages_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_audience_pages_hero_links_link_type";
  ALTER TABLE "audience_pages_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_audience_pages_hero_links_link_type" USING "link_type"::"public"."enum_audience_pages_hero_links_link_type";
  ALTER TABLE "audience_pages_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "audience_pages_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_audience_pages_blocks_content_columns_link_type";
  CREATE TYPE "public"."enum_audience_pages_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "audience_pages_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_audience_pages_blocks_content_columns_link_type";
  ALTER TABLE "audience_pages_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_audience_pages_blocks_content_columns_link_type" USING "link_type"::"public"."enum_audience_pages_blocks_content_columns_link_type";
  ALTER TABLE "audience_pages_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "audience_pages_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_audience_pages_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum_audience_pages_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "audience_pages_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_audience_pages_blocks_cta_links_link_type";
  ALTER TABLE "audience_pages_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_audience_pages_blocks_cta_links_link_type" USING "link_type"::"public"."enum_audience_pages_blocks_cta_links_link_type";
  ALTER TABLE "_audience_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_audience_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__audience_pages_v_version_hero_links_link_type";
  CREATE TYPE "public"."enum__audience_pages_v_version_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_audience_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__audience_pages_v_version_hero_links_link_type";
  ALTER TABLE "_audience_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__audience_pages_v_version_hero_links_link_type" USING "link_type"::"public"."enum__audience_pages_v_version_hero_links_link_type";
  ALTER TABLE "_audience_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_audience_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__audience_pages_v_blocks_content_columns_link_type";
  CREATE TYPE "public"."enum__audience_pages_v_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_audience_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__audience_pages_v_blocks_content_columns_link_type";
  ALTER TABLE "_audience_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__audience_pages_v_blocks_content_columns_link_type" USING "link_type"::"public"."enum__audience_pages_v_blocks_content_columns_link_type";
  ALTER TABLE "_audience_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_audience_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__audience_pages_v_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum__audience_pages_v_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_audience_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__audience_pages_v_blocks_cta_links_link_type";
  ALTER TABLE "_audience_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__audience_pages_v_blocks_cta_links_link_type" USING "link_type"::"public"."enum__audience_pages_v_blocks_cta_links_link_type";
  ALTER TABLE "home_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "home_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_home_blocks_content_columns_link_type";
  CREATE TYPE "public"."enum_home_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "home_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_home_blocks_content_columns_link_type";
  ALTER TABLE "home_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_home_blocks_content_columns_link_type" USING "link_type"::"public"."enum_home_blocks_content_columns_link_type";
  ALTER TABLE "home_stmt_links_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "home_stmt_links_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_home_stmt_links_links_link_type";
  CREATE TYPE "public"."enum_home_stmt_links_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "home_stmt_links_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_home_stmt_links_links_link_type";
  ALTER TABLE "home_stmt_links_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_home_stmt_links_links_link_type" USING "link_type"::"public"."enum_home_stmt_links_links_link_type";
  ALTER TABLE "home_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "home_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_home_blocks_testimonials_marquee_links_link_type";
  CREATE TYPE "public"."enum_home_blocks_testimonials_marquee_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "home_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_home_blocks_testimonials_marquee_links_link_type";
  ALTER TABLE "home_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_home_blocks_testimonials_marquee_links_link_type" USING "link_type"::"public"."enum_home_blocks_testimonials_marquee_links_link_type";
  ALTER TABLE "home_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "home_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_home_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum_home_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "home_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_home_blocks_cta_links_link_type";
  ALTER TABLE "home_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_home_blocks_cta_links_link_type" USING "link_type"::"public"."enum_home_blocks_cta_links_link_type";
  ALTER TABLE "_home_v_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_home_v_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__home_v_blocks_content_columns_link_type";
  CREATE TYPE "public"."enum__home_v_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_home_v_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__home_v_blocks_content_columns_link_type";
  ALTER TABLE "_home_v_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__home_v_blocks_content_columns_link_type" USING "link_type"::"public"."enum__home_v_blocks_content_columns_link_type";
  ALTER TABLE "__home_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "__home_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum___home_v_stmt_links_v_links_link_type";
  CREATE TYPE "public"."enum___home_v_stmt_links_v_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "__home_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum___home_v_stmt_links_v_links_link_type";
  ALTER TABLE "__home_v_stmt_links_v_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum___home_v_stmt_links_v_links_link_type" USING "link_type"::"public"."enum___home_v_stmt_links_v_links_link_type";
  ALTER TABLE "_home_v_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_home_v_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__home_v_blocks_testimonials_marquee_links_link_type";
  CREATE TYPE "public"."enum__home_v_blocks_testimonials_marquee_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_home_v_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__home_v_blocks_testimonials_marquee_links_link_type";
  ALTER TABLE "_home_v_blocks_testimonials_marquee_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__home_v_blocks_testimonials_marquee_links_link_type" USING "link_type"::"public"."enum__home_v_blocks_testimonials_marquee_links_link_type";
  ALTER TABLE "_home_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_home_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__home_v_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum__home_v_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_home_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__home_v_blocks_cta_links_link_type";
  ALTER TABLE "_home_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__home_v_blocks_cta_links_link_type" USING "link_type"::"public"."enum__home_v_blocks_cta_links_link_type";
  ALTER TABLE "insights_index_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "insights_index_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_insights_index_hero_links_link_type";
  CREATE TYPE "public"."enum_insights_index_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "insights_index_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_insights_index_hero_links_link_type";
  ALTER TABLE "insights_index_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_insights_index_hero_links_link_type" USING "link_type"::"public"."enum_insights_index_hero_links_link_type";
  ALTER TABLE "_insights_index_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_insights_index_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__insights_index_v_version_hero_links_link_type";
  CREATE TYPE "public"."enum__insights_index_v_version_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_insights_index_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__insights_index_v_version_hero_links_link_type";
  ALTER TABLE "_insights_index_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__insights_index_v_version_hero_links_link_type" USING "link_type"::"public"."enum__insights_index_v_version_hero_links_link_type";
  ALTER TABLE "works_index_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "works_index_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_works_index_hero_links_link_type";
  CREATE TYPE "public"."enum_works_index_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "works_index_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_works_index_hero_links_link_type";
  ALTER TABLE "works_index_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_works_index_hero_links_link_type" USING "link_type"::"public"."enum_works_index_hero_links_link_type";
  ALTER TABLE "_works_index_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_works_index_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__works_index_v_version_hero_links_link_type";
  CREATE TYPE "public"."enum__works_index_v_version_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_works_index_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__works_index_v_version_hero_links_link_type";
  ALTER TABLE "_works_index_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__works_index_v_version_hero_links_link_type" USING "link_type"::"public"."enum__works_index_v_version_hero_links_link_type";
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_header_nav_items_link_type";
  CREATE TYPE "public"."enum_header_nav_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_header_nav_items_link_type";
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_header_nav_items_link_type" USING "link_type"::"public"."enum_header_nav_items_link_type";
  ALTER TABLE "footer_closing_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "footer_closing_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_footer_closing_links_link_type";
  CREATE TYPE "public"."enum_footer_closing_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "footer_closing_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_footer_closing_links_link_type";
  ALTER TABLE "footer_closing_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_footer_closing_links_link_type" USING "link_type"::"public"."enum_footer_closing_links_link_type";
  ALTER TABLE "footer" ALTER COLUMN "get_in_touch_type" SET DATA TYPE text;
  ALTER TABLE "footer" ALTER COLUMN "get_in_touch_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_footer_get_in_touch_type";
  CREATE TYPE "public"."enum_footer_get_in_touch_type" AS ENUM('reference', 'custom');
  ALTER TABLE "footer" ALTER COLUMN "get_in_touch_type" SET DEFAULT 'reference'::"public"."enum_footer_get_in_touch_type";
  ALTER TABLE "footer" ALTER COLUMN "get_in_touch_type" SET DATA TYPE "public"."enum_footer_get_in_touch_type" USING "get_in_touch_type"::"public"."enum_footer_get_in_touch_type";
  ALTER TABLE "pages_hero_links" DROP COLUMN "link_site_page";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "link_site_page";
  ALTER TABLE "pages_stmt_links_links" DROP COLUMN "link_site_page";
  ALTER TABLE "pages_blocks_testimonials_marquee_links" DROP COLUMN "link_site_page";
  ALTER TABLE "pages_blocks_cta_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_pages_v_version_hero_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "link_site_page";
  ALTER TABLE "__pages_v_stmt_links_v_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_pages_v_blocks_testimonials_marquee_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_pages_v_blocks_cta_links" DROP COLUMN "link_site_page";
  ALTER TABLE "work_pages_stmt_links_links" DROP COLUMN "link_site_page";
  ALTER TABLE "__work_pages_v_stmt_links_v_links" DROP COLUMN "link_site_page";
  ALTER TABLE "expertise_pages_hero_links" DROP COLUMN "link_site_page";
  ALTER TABLE "expertise_pages_blocks_content_columns" DROP COLUMN "link_site_page";
  ALTER TABLE "expertise_pages_blocks_cta_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_expertise_pages_v_version_hero_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_expertise_pages_v_blocks_content_columns" DROP COLUMN "link_site_page";
  ALTER TABLE "_expertise_pages_v_blocks_cta_links" DROP COLUMN "link_site_page";
  ALTER TABLE "audience_pages_hero_links" DROP COLUMN "link_site_page";
  ALTER TABLE "audience_pages_blocks_content_columns" DROP COLUMN "link_site_page";
  ALTER TABLE "audience_pages_blocks_cta_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_audience_pages_v_version_hero_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_audience_pages_v_blocks_content_columns" DROP COLUMN "link_site_page";
  ALTER TABLE "_audience_pages_v_blocks_cta_links" DROP COLUMN "link_site_page";
  ALTER TABLE "home_blocks_content_columns" DROP COLUMN "link_site_page";
  ALTER TABLE "home_stmt_links_links" DROP COLUMN "link_site_page";
  ALTER TABLE "home_blocks_testimonials_marquee_links" DROP COLUMN "link_site_page";
  ALTER TABLE "home_blocks_cta_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_home_v_blocks_content_columns" DROP COLUMN "link_site_page";
  ALTER TABLE "__home_v_stmt_links_v_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_home_v_blocks_testimonials_marquee_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_home_v_blocks_cta_links" DROP COLUMN "link_site_page";
  ALTER TABLE "insights_index_hero_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_insights_index_v_version_hero_links" DROP COLUMN "link_site_page";
  ALTER TABLE "works_index_hero_links" DROP COLUMN "link_site_page";
  ALTER TABLE "_works_index_v_version_hero_links" DROP COLUMN "link_site_page";
  ALTER TABLE "header_nav_items" DROP COLUMN "link_site_page";
  ALTER TABLE "footer_closing_links" DROP COLUMN "link_site_page";
  ALTER TABLE "footer" DROP COLUMN "get_in_touch_site_page";
  DROP TYPE "public"."enum_pages_hero_links_link_site_page";
  DROP TYPE "public"."enum_pages_blocks_content_columns_link_site_page";
  DROP TYPE "public"."enum_pages_stmt_links_links_link_site_page";
  DROP TYPE "public"."enum_pages_blocks_testimonials_marquee_links_link_site_page";
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_site_page";
  DROP TYPE "public"."enum__pages_v_version_hero_links_link_site_page";
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_link_site_page";
  DROP TYPE "public"."enum___pages_v_stmt_links_v_links_link_site_page";
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_marquee_links_link_site_page";
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_site_page";
  DROP TYPE "public"."enum_work_pages_stmt_links_links_link_site_page";
  DROP TYPE "public"."enum___work_pages_v_stmt_links_v_links_link_site_page";
  DROP TYPE "public"."enum_expertise_pages_hero_links_link_site_page";
  DROP TYPE "public"."enum_expertise_pages_blocks_content_columns_link_site_page";
  DROP TYPE "public"."enum_expertise_pages_blocks_cta_links_link_site_page";
  DROP TYPE "public"."enum__expertise_pages_v_version_hero_links_link_site_page";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_content_columns_link_site_page";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_cta_links_link_site_page";
  DROP TYPE "public"."enum_audience_pages_hero_links_link_site_page";
  DROP TYPE "public"."enum_audience_pages_blocks_content_columns_link_site_page";
  DROP TYPE "public"."enum_audience_pages_blocks_cta_links_link_site_page";
  DROP TYPE "public"."enum__audience_pages_v_version_hero_links_link_site_page";
  DROP TYPE "public"."enum__audience_pages_v_blocks_content_columns_link_site_page";
  DROP TYPE "public"."enum__audience_pages_v_blocks_cta_links_link_site_page";
  DROP TYPE "public"."enum_home_blocks_content_columns_link_site_page";
  DROP TYPE "public"."enum_home_stmt_links_links_link_site_page";
  DROP TYPE "public"."enum_home_blocks_testimonials_marquee_links_link_site_page";
  DROP TYPE "public"."enum_home_blocks_cta_links_link_site_page";
  DROP TYPE "public"."enum__home_v_blocks_content_columns_link_site_page";
  DROP TYPE "public"."enum___home_v_stmt_links_v_links_link_site_page";
  DROP TYPE "public"."enum__home_v_blocks_testimonials_marquee_links_link_site_page";
  DROP TYPE "public"."enum__home_v_blocks_cta_links_link_site_page";
  DROP TYPE "public"."enum_insights_index_hero_links_link_site_page";
  DROP TYPE "public"."enum__insights_index_v_version_hero_links_link_site_page";
  DROP TYPE "public"."enum_works_index_hero_links_link_site_page";
  DROP TYPE "public"."enum__works_index_v_version_hero_links_link_site_page";
  DROP TYPE "public"."enum_header_nav_items_link_site_page";
  DROP TYPE "public"."enum_footer_closing_links_link_site_page";
  DROP TYPE "public"."enum_footer_get_in_touch_site_page";`)
}
