import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "work_pages_blocks_media_block" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "work_pages_blocks_carousel" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_work_pages_v_blocks_media_block" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_work_pages_v_blocks_carousel" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "pages_full_media" DROP COLUMN "browse_all_media";
  ALTER TABLE "pages_media_split" DROP COLUMN "browse_all_media";
  ALTER TABLE "pages_split_narrow" DROP COLUMN "browse_all_media";
  ALTER TABLE "pages_image_pair" DROP COLUMN "browse_all_media";
  ALTER TABLE "pages_split_offset" DROP COLUMN "browse_all_media";
  ALTER TABLE "pages_image_statement" DROP COLUMN "browse_all_media";
  ALTER TABLE "pages_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "pages_aud_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "pages_blocks_feature_statement_grid" DROP COLUMN "browse_all_media";
  ALTER TABLE "__pages_v_full_media_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__pages_v_media_split_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__pages_v_split_narrow_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__pages_v_image_pair_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__pages_v_split_offset_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__pages_v_image_statement_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "_pages_v_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "__pages_v_aud_tabs_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "_pages_v_blocks_feature_statement_grid" DROP COLUMN "browse_all_media";
  ALTER TABLE "posts_full_media" DROP COLUMN "browse_all_media";
  ALTER TABLE "posts_media_split" DROP COLUMN "browse_all_media";
  ALTER TABLE "posts_split_narrow" DROP COLUMN "browse_all_media";
  ALTER TABLE "posts_image_pair" DROP COLUMN "browse_all_media";
  ALTER TABLE "posts_split_offset" DROP COLUMN "browse_all_media";
  ALTER TABLE "posts_image_statement" DROP COLUMN "browse_all_media";
  ALTER TABLE "posts_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "__posts_v_full_media_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__posts_v_media_split_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__posts_v_split_narrow_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__posts_v_image_pair_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__posts_v_split_offset_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__posts_v_image_statement_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "_posts_v_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "lab_pages_full_media" DROP COLUMN "browse_all_media";
  ALTER TABLE "lab_pages_media_split" DROP COLUMN "browse_all_media";
  ALTER TABLE "lab_pages_split_narrow" DROP COLUMN "browse_all_media";
  ALTER TABLE "lab_pages_image_pair" DROP COLUMN "browse_all_media";
  ALTER TABLE "lab_pages_split_offset" DROP COLUMN "browse_all_media";
  ALTER TABLE "lab_pages_image_statement" DROP COLUMN "browse_all_media";
  ALTER TABLE "lab_pages_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "lab_pages_scroll_gal" DROP COLUMN "browse_all_media";
  ALTER TABLE "__lab_pages_v_full_media_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__lab_pages_v_media_split_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__lab_pages_v_split_narrow_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__lab_pages_v_image_pair_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__lab_pages_v_split_offset_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__lab_pages_v_image_statement_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "__lab_pages_v_scroll_gal_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "expertise_pages_full_media" DROP COLUMN "browse_all_media";
  ALTER TABLE "expertise_pages_media_split" DROP COLUMN "browse_all_media";
  ALTER TABLE "expertise_pages_split_narrow" DROP COLUMN "browse_all_media";
  ALTER TABLE "expertise_pages_image_pair" DROP COLUMN "browse_all_media";
  ALTER TABLE "expertise_pages_split_offset" DROP COLUMN "browse_all_media";
  ALTER TABLE "expertise_pages_image_statement" DROP COLUMN "browse_all_media";
  ALTER TABLE "expertise_pages_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "expertise_pages_aud_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "expertise_pages_blocks_feature_statement_grid" DROP COLUMN "browse_all_media";
  ALTER TABLE "__expertise_pages_v_full_media_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__expertise_pages_v_media_split_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__expertise_pages_v_split_narrow_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__expertise_pages_v_image_pair_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__expertise_pages_v_split_offset_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__expertise_pages_v_image_statement_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "__expertise_pages_v_aud_tabs_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "_expertise_pages_v_blocks_feature_statement_grid" DROP COLUMN "browse_all_media";
  ALTER TABLE "audience_pages_full_media" DROP COLUMN "browse_all_media";
  ALTER TABLE "audience_pages_media_split" DROP COLUMN "browse_all_media";
  ALTER TABLE "audience_pages_split_narrow" DROP COLUMN "browse_all_media";
  ALTER TABLE "audience_pages_image_pair" DROP COLUMN "browse_all_media";
  ALTER TABLE "audience_pages_split_offset" DROP COLUMN "browse_all_media";
  ALTER TABLE "audience_pages_image_statement" DROP COLUMN "browse_all_media";
  ALTER TABLE "audience_pages_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "audience_pages_aud_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "audience_pages_blocks_feature_statement_grid" DROP COLUMN "browse_all_media";
  ALTER TABLE "__audience_pages_v_full_media_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__audience_pages_v_media_split_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__audience_pages_v_split_narrow_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__audience_pages_v_image_pair_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__audience_pages_v_split_offset_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__audience_pages_v_image_statement_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "__audience_pages_v_aud_tabs_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "_audience_pages_v_blocks_feature_statement_grid" DROP COLUMN "browse_all_media";
  ALTER TABLE "home_full_media" DROP COLUMN "browse_all_media";
  ALTER TABLE "home_media_split" DROP COLUMN "browse_all_media";
  ALTER TABLE "home_split_narrow" DROP COLUMN "browse_all_media";
  ALTER TABLE "home_image_statement" DROP COLUMN "browse_all_media";
  ALTER TABLE "home_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "home_aud_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "home_blocks_feature_statement_grid" DROP COLUMN "browse_all_media";
  ALTER TABLE "__home_v_full_media_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__home_v_media_split_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__home_v_split_narrow_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "__home_v_image_statement_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "_home_v_blocks_feature_tabs" DROP COLUMN "browse_all_media";
  ALTER TABLE "__home_v_aud_tabs_v" DROP COLUMN "browse_all_media";
  ALTER TABLE "_home_v_blocks_feature_statement_grid" DROP COLUMN "browse_all_media";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_full_media" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "pages_media_split" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "pages_split_narrow" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "pages_image_pair" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "pages_split_offset" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "pages_image_statement" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "pages_aud_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_feature_statement_grid" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__pages_v_full_media_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__pages_v_media_split_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__pages_v_split_narrow_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__pages_v_image_pair_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__pages_v_split_offset_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__pages_v_image_statement_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__pages_v_aud_tabs_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_feature_statement_grid" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "posts_full_media" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "posts_media_split" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "posts_split_narrow" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "posts_image_pair" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "posts_split_offset" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "posts_image_statement" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__posts_v_full_media_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__posts_v_media_split_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__posts_v_split_narrow_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__posts_v_image_pair_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__posts_v_split_offset_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__posts_v_image_statement_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_full_media" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_media_split" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_split_narrow" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_image_pair" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_split_offset" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_image_statement" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages_scroll_gal" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_full_media_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_media_split_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_split_narrow_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_image_pair_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_split_offset_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_image_statement_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_lab_pages_v_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__lab_pages_v_scroll_gal_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_full_media" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_media_split" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_split_narrow" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_image_pair" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_split_offset" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_image_statement" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_aud_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages_blocks_feature_statement_grid" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_full_media_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_media_split_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_split_narrow_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_image_pair_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_split_offset_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_image_statement_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__expertise_pages_v_aud_tabs_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_expertise_pages_v_blocks_feature_statement_grid" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_full_media" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_media_split" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_split_narrow" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_image_pair" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_split_offset" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_image_statement" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_aud_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages_blocks_feature_statement_grid" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_full_media_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_media_split_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_split_narrow_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_image_pair_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_split_offset_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_image_statement_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__audience_pages_v_aud_tabs_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_audience_pages_v_blocks_feature_statement_grid" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "home_full_media" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "home_media_split" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "home_split_narrow" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "home_image_statement" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "home_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "home_aud_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "home_blocks_feature_statement_grid" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__home_v_full_media_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__home_v_media_split_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__home_v_split_narrow_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__home_v_image_statement_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_home_v_blocks_feature_tabs" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "__home_v_aud_tabs_v" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "_home_v_blocks_feature_statement_grid" ADD COLUMN "browse_all_media" boolean DEFAULT false;
  ALTER TABLE "work_pages_blocks_media_block" DROP COLUMN "browse_all_media";
  ALTER TABLE "work_pages_blocks_carousel" DROP COLUMN "browse_all_media";
  ALTER TABLE "_work_pages_v_blocks_media_block" DROP COLUMN "browse_all_media";
  ALTER TABLE "_work_pages_v_blocks_carousel" DROP COLUMN "browse_all_media";`)
}
