import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_content_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_blocks_media_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_blocks_feature_statement_grid_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_blocks_feature_heading_offset_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_image_statement_aspect_ratio" AS ENUM('responsive', '16-9', '3-2', '21-9');
  CREATE TYPE "public"."enum_pages_image_statement_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_blocks_feature_tabs_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_blocks_testimonials_marquee_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_blocks_archive_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_blocks_cta_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_blocks_form_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_pages_blocks_newsletter_signup_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_content_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_feature_statement_grid_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_feature_heading_offset_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum___pages_v_image_statement_v_aspect_ratio" AS ENUM('responsive', '16-9', '3-2', '21-9');
  CREATE TYPE "public"."enum___pages_v_image_statement_v_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_feature_tabs_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_marquee_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__pages_v_blocks_newsletter_signup_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_work_pages_blocks_feature_statement_grid_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_work_pages_blocks_feature_heading_offset_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_work_pages_image_statement_aspect_ratio" AS ENUM('responsive', '16-9', '3-2', '21-9');
  CREATE TYPE "public"."enum_work_pages_image_statement_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_work_pages_blocks_feature_tabs_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_work_pages_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__work_pages_v_blocks_feature_statement_grid_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__work_pages_v_blocks_feature_heading_offset_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum___work_pages_v_image_statement_v_aspect_ratio" AS ENUM('responsive', '16-9', '3-2', '21-9');
  CREATE TYPE "public"."enum___work_pages_v_image_statement_v_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__work_pages_v_blocks_feature_tabs_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__work_pages_v_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_lab_pages_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__lab_pages_v_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_expertise_pages_blocks_content_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_expertise_pages_blocks_media_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_expertise_pages_blocks_feature_statement_grid_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_expertise_pages_blocks_feature_heading_offset_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_expertise_pages_image_statement_aspect_ratio" AS ENUM('responsive', '16-9', '3-2', '21-9');
  CREATE TYPE "public"."enum_expertise_pages_image_statement_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_expertise_pages_blocks_feature_tabs_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_expertise_pages_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_expertise_pages_blocks_archive_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_expertise_pages_blocks_cta_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_expertise_pages_blocks_form_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_content_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_media_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_feature_statement_grid_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_feature_heading_offset_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum___expertise_pages_v_image_statement_v_aspect_ratio" AS ENUM('responsive', '16-9', '3-2', '21-9');
  CREATE TYPE "public"."enum___expertise_pages_v_image_statement_v_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_feature_tabs_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_archive_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_cta_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__expertise_pages_v_blocks_form_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_audience_pages_blocks_content_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_audience_pages_blocks_media_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_audience_pages_blocks_feature_statement_grid_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_audience_pages_blocks_feature_heading_offset_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_audience_pages_image_statement_aspect_ratio" AS ENUM('responsive', '16-9', '3-2', '21-9');
  CREATE TYPE "public"."enum_audience_pages_image_statement_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_audience_pages_blocks_feature_tabs_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_audience_pages_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_audience_pages_blocks_archive_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_audience_pages_blocks_cta_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_audience_pages_blocks_form_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_content_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_media_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_feature_statement_grid_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_feature_heading_offset_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum___audience_pages_v_image_statement_v_aspect_ratio" AS ENUM('responsive', '16-9', '3-2', '21-9');
  CREATE TYPE "public"."enum___audience_pages_v_image_statement_v_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_feature_tabs_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_archive_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_cta_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__audience_pages_v_blocks_form_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_content_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_media_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_feature_statement_grid_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_feature_heading_offset_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_image_statement_aspect_ratio" AS ENUM('responsive', '16-9', '3-2', '21-9');
  CREATE TYPE "public"."enum_home_image_statement_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_feature_tabs_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_testimonials_marquee_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_archive_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_cta_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_form_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum_home_blocks_newsletter_signup_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_content_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_media_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_feature_statement_grid_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_feature_heading_offset_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum___home_v_image_statement_v_aspect_ratio" AS ENUM('responsive', '16-9', '3-2', '21-9');
  CREATE TYPE "public"."enum___home_v_image_statement_v_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_feature_tabs_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_testimonials_marquee_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_carousel_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_archive_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_cta_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_form_block_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  CREATE TYPE "public"."enum__home_v_blocks_newsletter_signup_theme" AS ENUM('light', 'dark', 'neutral', 'brand');
  ALTER TABLE "pages_blocks_content" ADD COLUMN "theme" "enum_pages_blocks_content_theme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "theme" "enum_pages_blocks_media_block_theme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_feature_statement_grid" ADD COLUMN "theme" "enum_pages_blocks_feature_statement_grid_theme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_feature_heading_offset" ADD COLUMN "theme" "enum_pages_blocks_feature_heading_offset_theme" DEFAULT 'light';
  ALTER TABLE "pages_image_statement" ADD COLUMN "aspect_ratio" "enum_pages_image_statement_aspect_ratio" DEFAULT 'responsive';
  ALTER TABLE "pages_image_statement" ADD COLUMN "theme" "enum_pages_image_statement_theme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_feature_tabs" ADD COLUMN "theme" "enum_pages_blocks_feature_tabs_theme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_testimonials_marquee" ADD COLUMN "theme" "enum_pages_blocks_testimonials_marquee_theme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_carousel" ADD COLUMN "theme" "enum_pages_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "theme" "enum_pages_blocks_archive_theme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "theme" "enum_pages_blocks_cta_theme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "theme" "enum_pages_blocks_form_block_theme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_newsletter_signup" ADD COLUMN "theme" "enum_pages_blocks_newsletter_signup_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "theme" "enum__pages_v_blocks_content_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "theme" "enum__pages_v_blocks_media_block_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_feature_statement_grid" ADD COLUMN "theme" "enum__pages_v_blocks_feature_statement_grid_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_feature_heading_offset" ADD COLUMN "theme" "enum__pages_v_blocks_feature_heading_offset_theme" DEFAULT 'light';
  ALTER TABLE "__pages_v_image_statement_v" ADD COLUMN "aspect_ratio" "enum___pages_v_image_statement_v_aspect_ratio" DEFAULT 'responsive';
  ALTER TABLE "__pages_v_image_statement_v" ADD COLUMN "theme" "enum___pages_v_image_statement_v_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_feature_tabs" ADD COLUMN "theme" "enum__pages_v_blocks_feature_tabs_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_testimonials_marquee" ADD COLUMN "theme" "enum__pages_v_blocks_testimonials_marquee_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_carousel" ADD COLUMN "theme" "enum__pages_v_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "theme" "enum__pages_v_blocks_archive_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "theme" "enum__pages_v_blocks_cta_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "theme" "enum__pages_v_blocks_form_block_theme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_newsletter_signup" ADD COLUMN "theme" "enum__pages_v_blocks_newsletter_signup_theme" DEFAULT 'light';
  ALTER TABLE "work_pages_blocks_feature_statement_grid" ADD COLUMN "theme" "enum_work_pages_blocks_feature_statement_grid_theme" DEFAULT 'light';
  ALTER TABLE "work_pages_blocks_feature_heading_offset" ADD COLUMN "theme" "enum_work_pages_blocks_feature_heading_offset_theme" DEFAULT 'light';
  ALTER TABLE "work_pages_image_statement" ADD COLUMN "aspect_ratio" "enum_work_pages_image_statement_aspect_ratio" DEFAULT 'responsive';
  ALTER TABLE "work_pages_image_statement" ADD COLUMN "theme" "enum_work_pages_image_statement_theme" DEFAULT 'light';
  ALTER TABLE "work_pages_blocks_feature_tabs" ADD COLUMN "theme" "enum_work_pages_blocks_feature_tabs_theme" DEFAULT 'light';
  ALTER TABLE "work_pages_blocks_carousel" ADD COLUMN "theme" "enum_work_pages_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "_work_pages_v_blocks_feature_statement_grid" ADD COLUMN "theme" "enum__work_pages_v_blocks_feature_statement_grid_theme" DEFAULT 'light';
  ALTER TABLE "_work_pages_v_blocks_feature_heading_offset" ADD COLUMN "theme" "enum__work_pages_v_blocks_feature_heading_offset_theme" DEFAULT 'light';
  ALTER TABLE "__work_pages_v_image_statement_v" ADD COLUMN "aspect_ratio" "enum___work_pages_v_image_statement_v_aspect_ratio" DEFAULT 'responsive';
  ALTER TABLE "__work_pages_v_image_statement_v" ADD COLUMN "theme" "enum___work_pages_v_image_statement_v_theme" DEFAULT 'light';
  ALTER TABLE "_work_pages_v_blocks_feature_tabs" ADD COLUMN "theme" "enum__work_pages_v_blocks_feature_tabs_theme" DEFAULT 'light';
  ALTER TABLE "_work_pages_v_blocks_carousel" ADD COLUMN "theme" "enum__work_pages_v_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "lab_pages_blocks_carousel" ADD COLUMN "theme" "enum_lab_pages_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "_lab_pages_v_blocks_carousel" ADD COLUMN "theme" "enum__lab_pages_v_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "expertise_pages_blocks_content" ADD COLUMN "theme" "enum_expertise_pages_blocks_content_theme" DEFAULT 'light';
  ALTER TABLE "expertise_pages_blocks_media_block" ADD COLUMN "theme" "enum_expertise_pages_blocks_media_block_theme" DEFAULT 'light';
  ALTER TABLE "expertise_pages_blocks_feature_statement_grid" ADD COLUMN "theme" "enum_expertise_pages_blocks_feature_statement_grid_theme" DEFAULT 'light';
  ALTER TABLE "expertise_pages_blocks_feature_heading_offset" ADD COLUMN "theme" "enum_expertise_pages_blocks_feature_heading_offset_theme" DEFAULT 'light';
  ALTER TABLE "expertise_pages_image_statement" ADD COLUMN "aspect_ratio" "enum_expertise_pages_image_statement_aspect_ratio" DEFAULT 'responsive';
  ALTER TABLE "expertise_pages_image_statement" ADD COLUMN "theme" "enum_expertise_pages_image_statement_theme" DEFAULT 'light';
  ALTER TABLE "expertise_pages_blocks_feature_tabs" ADD COLUMN "theme" "enum_expertise_pages_blocks_feature_tabs_theme" DEFAULT 'light';
  ALTER TABLE "expertise_pages_blocks_carousel" ADD COLUMN "theme" "enum_expertise_pages_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "expertise_pages_blocks_archive" ADD COLUMN "theme" "enum_expertise_pages_blocks_archive_theme" DEFAULT 'light';
  ALTER TABLE "expertise_pages_blocks_cta" ADD COLUMN "theme" "enum_expertise_pages_blocks_cta_theme" DEFAULT 'light';
  ALTER TABLE "expertise_pages_blocks_form_block" ADD COLUMN "theme" "enum_expertise_pages_blocks_form_block_theme" DEFAULT 'light';
  ALTER TABLE "_expertise_pages_v_blocks_content" ADD COLUMN "theme" "enum__expertise_pages_v_blocks_content_theme" DEFAULT 'light';
  ALTER TABLE "_expertise_pages_v_blocks_media_block" ADD COLUMN "theme" "enum__expertise_pages_v_blocks_media_block_theme" DEFAULT 'light';
  ALTER TABLE "_expertise_pages_v_blocks_feature_statement_grid" ADD COLUMN "theme" "enum__expertise_pages_v_blocks_feature_statement_grid_theme" DEFAULT 'light';
  ALTER TABLE "_expertise_pages_v_blocks_feature_heading_offset" ADD COLUMN "theme" "enum__expertise_pages_v_blocks_feature_heading_offset_theme" DEFAULT 'light';
  ALTER TABLE "__expertise_pages_v_image_statement_v" ADD COLUMN "aspect_ratio" "enum___expertise_pages_v_image_statement_v_aspect_ratio" DEFAULT 'responsive';
  ALTER TABLE "__expertise_pages_v_image_statement_v" ADD COLUMN "theme" "enum___expertise_pages_v_image_statement_v_theme" DEFAULT 'light';
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs" ADD COLUMN "theme" "enum__expertise_pages_v_blocks_feature_tabs_theme" DEFAULT 'light';
  ALTER TABLE "_expertise_pages_v_blocks_carousel" ADD COLUMN "theme" "enum__expertise_pages_v_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "_expertise_pages_v_blocks_archive" ADD COLUMN "theme" "enum__expertise_pages_v_blocks_archive_theme" DEFAULT 'light';
  ALTER TABLE "_expertise_pages_v_blocks_cta" ADD COLUMN "theme" "enum__expertise_pages_v_blocks_cta_theme" DEFAULT 'light';
  ALTER TABLE "_expertise_pages_v_blocks_form_block" ADD COLUMN "theme" "enum__expertise_pages_v_blocks_form_block_theme" DEFAULT 'light';
  ALTER TABLE "audience_pages_blocks_content" ADD COLUMN "theme" "enum_audience_pages_blocks_content_theme" DEFAULT 'light';
  ALTER TABLE "audience_pages_blocks_media_block" ADD COLUMN "theme" "enum_audience_pages_blocks_media_block_theme" DEFAULT 'light';
  ALTER TABLE "audience_pages_blocks_feature_statement_grid" ADD COLUMN "theme" "enum_audience_pages_blocks_feature_statement_grid_theme" DEFAULT 'light';
  ALTER TABLE "audience_pages_blocks_feature_heading_offset" ADD COLUMN "theme" "enum_audience_pages_blocks_feature_heading_offset_theme" DEFAULT 'light';
  ALTER TABLE "audience_pages_image_statement" ADD COLUMN "aspect_ratio" "enum_audience_pages_image_statement_aspect_ratio" DEFAULT 'responsive';
  ALTER TABLE "audience_pages_image_statement" ADD COLUMN "theme" "enum_audience_pages_image_statement_theme" DEFAULT 'light';
  ALTER TABLE "audience_pages_blocks_feature_tabs" ADD COLUMN "theme" "enum_audience_pages_blocks_feature_tabs_theme" DEFAULT 'light';
  ALTER TABLE "audience_pages_blocks_carousel" ADD COLUMN "theme" "enum_audience_pages_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "audience_pages_blocks_archive" ADD COLUMN "theme" "enum_audience_pages_blocks_archive_theme" DEFAULT 'light';
  ALTER TABLE "audience_pages_blocks_cta" ADD COLUMN "theme" "enum_audience_pages_blocks_cta_theme" DEFAULT 'light';
  ALTER TABLE "audience_pages_blocks_form_block" ADD COLUMN "theme" "enum_audience_pages_blocks_form_block_theme" DEFAULT 'light';
  ALTER TABLE "_audience_pages_v_blocks_content" ADD COLUMN "theme" "enum__audience_pages_v_blocks_content_theme" DEFAULT 'light';
  ALTER TABLE "_audience_pages_v_blocks_media_block" ADD COLUMN "theme" "enum__audience_pages_v_blocks_media_block_theme" DEFAULT 'light';
  ALTER TABLE "_audience_pages_v_blocks_feature_statement_grid" ADD COLUMN "theme" "enum__audience_pages_v_blocks_feature_statement_grid_theme" DEFAULT 'light';
  ALTER TABLE "_audience_pages_v_blocks_feature_heading_offset" ADD COLUMN "theme" "enum__audience_pages_v_blocks_feature_heading_offset_theme" DEFAULT 'light';
  ALTER TABLE "__audience_pages_v_image_statement_v" ADD COLUMN "aspect_ratio" "enum___audience_pages_v_image_statement_v_aspect_ratio" DEFAULT 'responsive';
  ALTER TABLE "__audience_pages_v_image_statement_v" ADD COLUMN "theme" "enum___audience_pages_v_image_statement_v_theme" DEFAULT 'light';
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs" ADD COLUMN "theme" "enum__audience_pages_v_blocks_feature_tabs_theme" DEFAULT 'light';
  ALTER TABLE "_audience_pages_v_blocks_carousel" ADD COLUMN "theme" "enum__audience_pages_v_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "_audience_pages_v_blocks_archive" ADD COLUMN "theme" "enum__audience_pages_v_blocks_archive_theme" DEFAULT 'light';
  ALTER TABLE "_audience_pages_v_blocks_cta" ADD COLUMN "theme" "enum__audience_pages_v_blocks_cta_theme" DEFAULT 'light';
  ALTER TABLE "_audience_pages_v_blocks_form_block" ADD COLUMN "theme" "enum__audience_pages_v_blocks_form_block_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_content" ADD COLUMN "theme" "enum_home_blocks_content_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_media_block" ADD COLUMN "theme" "enum_home_blocks_media_block_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_feature_statement_grid" ADD COLUMN "theme" "enum_home_blocks_feature_statement_grid_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_feature_heading_offset" ADD COLUMN "theme" "enum_home_blocks_feature_heading_offset_theme" DEFAULT 'light';
  ALTER TABLE "home_image_statement" ADD COLUMN "aspect_ratio" "enum_home_image_statement_aspect_ratio" DEFAULT 'responsive';
  ALTER TABLE "home_image_statement" ADD COLUMN "theme" "enum_home_image_statement_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_feature_tabs" ADD COLUMN "theme" "enum_home_blocks_feature_tabs_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_testimonials_marquee" ADD COLUMN "theme" "enum_home_blocks_testimonials_marquee_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_carousel" ADD COLUMN "theme" "enum_home_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_archive" ADD COLUMN "theme" "enum_home_blocks_archive_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_cta" ADD COLUMN "theme" "enum_home_blocks_cta_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_form_block" ADD COLUMN "theme" "enum_home_blocks_form_block_theme" DEFAULT 'light';
  ALTER TABLE "home_blocks_newsletter_signup" ADD COLUMN "theme" "enum_home_blocks_newsletter_signup_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_content" ADD COLUMN "theme" "enum__home_v_blocks_content_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_media_block" ADD COLUMN "theme" "enum__home_v_blocks_media_block_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_feature_statement_grid" ADD COLUMN "theme" "enum__home_v_blocks_feature_statement_grid_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_feature_heading_offset" ADD COLUMN "theme" "enum__home_v_blocks_feature_heading_offset_theme" DEFAULT 'light';
  ALTER TABLE "__home_v_image_statement_v" ADD COLUMN "aspect_ratio" "enum___home_v_image_statement_v_aspect_ratio" DEFAULT 'responsive';
  ALTER TABLE "__home_v_image_statement_v" ADD COLUMN "theme" "enum___home_v_image_statement_v_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_feature_tabs" ADD COLUMN "theme" "enum__home_v_blocks_feature_tabs_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_testimonials_marquee" ADD COLUMN "theme" "enum__home_v_blocks_testimonials_marquee_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_carousel" ADD COLUMN "theme" "enum__home_v_blocks_carousel_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_archive" ADD COLUMN "theme" "enum__home_v_blocks_archive_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_cta" ADD COLUMN "theme" "enum__home_v_blocks_cta_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_form_block" ADD COLUMN "theme" "enum__home_v_blocks_form_block_theme" DEFAULT 'light';
  ALTER TABLE "_home_v_blocks_newsletter_signup" ADD COLUMN "theme" "enum__home_v_blocks_newsletter_signup_theme" DEFAULT 'light';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_content" DROP COLUMN "theme";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "theme";
  ALTER TABLE "pages_blocks_feature_statement_grid" DROP COLUMN "theme";
  ALTER TABLE "pages_blocks_feature_heading_offset" DROP COLUMN "theme";
  ALTER TABLE "pages_image_statement" DROP COLUMN "aspect_ratio";
  ALTER TABLE "pages_image_statement" DROP COLUMN "theme";
  ALTER TABLE "pages_blocks_feature_tabs" DROP COLUMN "theme";
  ALTER TABLE "pages_blocks_testimonials_marquee" DROP COLUMN "theme";
  ALTER TABLE "pages_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "theme";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "theme";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "theme";
  ALTER TABLE "pages_blocks_newsletter_signup" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_feature_statement_grid" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_feature_heading_offset" DROP COLUMN "theme";
  ALTER TABLE "__pages_v_image_statement_v" DROP COLUMN "aspect_ratio";
  ALTER TABLE "__pages_v_image_statement_v" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_feature_tabs" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_testimonials_marquee" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "theme";
  ALTER TABLE "_pages_v_blocks_newsletter_signup" DROP COLUMN "theme";
  ALTER TABLE "work_pages_blocks_feature_statement_grid" DROP COLUMN "theme";
  ALTER TABLE "work_pages_blocks_feature_heading_offset" DROP COLUMN "theme";
  ALTER TABLE "work_pages_image_statement" DROP COLUMN "aspect_ratio";
  ALTER TABLE "work_pages_image_statement" DROP COLUMN "theme";
  ALTER TABLE "work_pages_blocks_feature_tabs" DROP COLUMN "theme";
  ALTER TABLE "work_pages_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "_work_pages_v_blocks_feature_statement_grid" DROP COLUMN "theme";
  ALTER TABLE "_work_pages_v_blocks_feature_heading_offset" DROP COLUMN "theme";
  ALTER TABLE "__work_pages_v_image_statement_v" DROP COLUMN "aspect_ratio";
  ALTER TABLE "__work_pages_v_image_statement_v" DROP COLUMN "theme";
  ALTER TABLE "_work_pages_v_blocks_feature_tabs" DROP COLUMN "theme";
  ALTER TABLE "_work_pages_v_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "lab_pages_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "_lab_pages_v_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "expertise_pages_blocks_content" DROP COLUMN "theme";
  ALTER TABLE "expertise_pages_blocks_media_block" DROP COLUMN "theme";
  ALTER TABLE "expertise_pages_blocks_feature_statement_grid" DROP COLUMN "theme";
  ALTER TABLE "expertise_pages_blocks_feature_heading_offset" DROP COLUMN "theme";
  ALTER TABLE "expertise_pages_image_statement" DROP COLUMN "aspect_ratio";
  ALTER TABLE "expertise_pages_image_statement" DROP COLUMN "theme";
  ALTER TABLE "expertise_pages_blocks_feature_tabs" DROP COLUMN "theme";
  ALTER TABLE "expertise_pages_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "expertise_pages_blocks_archive" DROP COLUMN "theme";
  ALTER TABLE "expertise_pages_blocks_cta" DROP COLUMN "theme";
  ALTER TABLE "expertise_pages_blocks_form_block" DROP COLUMN "theme";
  ALTER TABLE "_expertise_pages_v_blocks_content" DROP COLUMN "theme";
  ALTER TABLE "_expertise_pages_v_blocks_media_block" DROP COLUMN "theme";
  ALTER TABLE "_expertise_pages_v_blocks_feature_statement_grid" DROP COLUMN "theme";
  ALTER TABLE "_expertise_pages_v_blocks_feature_heading_offset" DROP COLUMN "theme";
  ALTER TABLE "__expertise_pages_v_image_statement_v" DROP COLUMN "aspect_ratio";
  ALTER TABLE "__expertise_pages_v_image_statement_v" DROP COLUMN "theme";
  ALTER TABLE "_expertise_pages_v_blocks_feature_tabs" DROP COLUMN "theme";
  ALTER TABLE "_expertise_pages_v_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "_expertise_pages_v_blocks_archive" DROP COLUMN "theme";
  ALTER TABLE "_expertise_pages_v_blocks_cta" DROP COLUMN "theme";
  ALTER TABLE "_expertise_pages_v_blocks_form_block" DROP COLUMN "theme";
  ALTER TABLE "audience_pages_blocks_content" DROP COLUMN "theme";
  ALTER TABLE "audience_pages_blocks_media_block" DROP COLUMN "theme";
  ALTER TABLE "audience_pages_blocks_feature_statement_grid" DROP COLUMN "theme";
  ALTER TABLE "audience_pages_blocks_feature_heading_offset" DROP COLUMN "theme";
  ALTER TABLE "audience_pages_image_statement" DROP COLUMN "aspect_ratio";
  ALTER TABLE "audience_pages_image_statement" DROP COLUMN "theme";
  ALTER TABLE "audience_pages_blocks_feature_tabs" DROP COLUMN "theme";
  ALTER TABLE "audience_pages_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "audience_pages_blocks_archive" DROP COLUMN "theme";
  ALTER TABLE "audience_pages_blocks_cta" DROP COLUMN "theme";
  ALTER TABLE "audience_pages_blocks_form_block" DROP COLUMN "theme";
  ALTER TABLE "_audience_pages_v_blocks_content" DROP COLUMN "theme";
  ALTER TABLE "_audience_pages_v_blocks_media_block" DROP COLUMN "theme";
  ALTER TABLE "_audience_pages_v_blocks_feature_statement_grid" DROP COLUMN "theme";
  ALTER TABLE "_audience_pages_v_blocks_feature_heading_offset" DROP COLUMN "theme";
  ALTER TABLE "__audience_pages_v_image_statement_v" DROP COLUMN "aspect_ratio";
  ALTER TABLE "__audience_pages_v_image_statement_v" DROP COLUMN "theme";
  ALTER TABLE "_audience_pages_v_blocks_feature_tabs" DROP COLUMN "theme";
  ALTER TABLE "_audience_pages_v_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "_audience_pages_v_blocks_archive" DROP COLUMN "theme";
  ALTER TABLE "_audience_pages_v_blocks_cta" DROP COLUMN "theme";
  ALTER TABLE "_audience_pages_v_blocks_form_block" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_content" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_media_block" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_feature_statement_grid" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_feature_heading_offset" DROP COLUMN "theme";
  ALTER TABLE "home_image_statement" DROP COLUMN "aspect_ratio";
  ALTER TABLE "home_image_statement" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_feature_tabs" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_testimonials_marquee" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_archive" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_cta" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_form_block" DROP COLUMN "theme";
  ALTER TABLE "home_blocks_newsletter_signup" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_content" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_media_block" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_feature_statement_grid" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_feature_heading_offset" DROP COLUMN "theme";
  ALTER TABLE "__home_v_image_statement_v" DROP COLUMN "aspect_ratio";
  ALTER TABLE "__home_v_image_statement_v" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_feature_tabs" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_testimonials_marquee" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_carousel" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_archive" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_cta" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_form_block" DROP COLUMN "theme";
  ALTER TABLE "_home_v_blocks_newsletter_signup" DROP COLUMN "theme";
  DROP TYPE "public"."enum_pages_blocks_content_theme";
  DROP TYPE "public"."enum_pages_blocks_media_block_theme";
  DROP TYPE "public"."enum_pages_blocks_feature_statement_grid_theme";
  DROP TYPE "public"."enum_pages_blocks_feature_heading_offset_theme";
  DROP TYPE "public"."enum_pages_image_statement_aspect_ratio";
  DROP TYPE "public"."enum_pages_image_statement_theme";
  DROP TYPE "public"."enum_pages_blocks_feature_tabs_theme";
  DROP TYPE "public"."enum_pages_blocks_testimonials_marquee_theme";
  DROP TYPE "public"."enum_pages_blocks_carousel_theme";
  DROP TYPE "public"."enum_pages_blocks_archive_theme";
  DROP TYPE "public"."enum_pages_blocks_cta_theme";
  DROP TYPE "public"."enum_pages_blocks_form_block_theme";
  DROP TYPE "public"."enum_pages_blocks_newsletter_signup_theme";
  DROP TYPE "public"."enum__pages_v_blocks_content_theme";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_theme";
  DROP TYPE "public"."enum__pages_v_blocks_feature_statement_grid_theme";
  DROP TYPE "public"."enum__pages_v_blocks_feature_heading_offset_theme";
  DROP TYPE "public"."enum___pages_v_image_statement_v_aspect_ratio";
  DROP TYPE "public"."enum___pages_v_image_statement_v_theme";
  DROP TYPE "public"."enum__pages_v_blocks_feature_tabs_theme";
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_marquee_theme";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_theme";
  DROP TYPE "public"."enum__pages_v_blocks_archive_theme";
  DROP TYPE "public"."enum__pages_v_blocks_cta_theme";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_theme";
  DROP TYPE "public"."enum__pages_v_blocks_newsletter_signup_theme";
  DROP TYPE "public"."enum_work_pages_blocks_feature_statement_grid_theme";
  DROP TYPE "public"."enum_work_pages_blocks_feature_heading_offset_theme";
  DROP TYPE "public"."enum_work_pages_image_statement_aspect_ratio";
  DROP TYPE "public"."enum_work_pages_image_statement_theme";
  DROP TYPE "public"."enum_work_pages_blocks_feature_tabs_theme";
  DROP TYPE "public"."enum_work_pages_blocks_carousel_theme";
  DROP TYPE "public"."enum__work_pages_v_blocks_feature_statement_grid_theme";
  DROP TYPE "public"."enum__work_pages_v_blocks_feature_heading_offset_theme";
  DROP TYPE "public"."enum___work_pages_v_image_statement_v_aspect_ratio";
  DROP TYPE "public"."enum___work_pages_v_image_statement_v_theme";
  DROP TYPE "public"."enum__work_pages_v_blocks_feature_tabs_theme";
  DROP TYPE "public"."enum__work_pages_v_blocks_carousel_theme";
  DROP TYPE "public"."enum_lab_pages_blocks_carousel_theme";
  DROP TYPE "public"."enum__lab_pages_v_blocks_carousel_theme";
  DROP TYPE "public"."enum_expertise_pages_blocks_content_theme";
  DROP TYPE "public"."enum_expertise_pages_blocks_media_block_theme";
  DROP TYPE "public"."enum_expertise_pages_blocks_feature_statement_grid_theme";
  DROP TYPE "public"."enum_expertise_pages_blocks_feature_heading_offset_theme";
  DROP TYPE "public"."enum_expertise_pages_image_statement_aspect_ratio";
  DROP TYPE "public"."enum_expertise_pages_image_statement_theme";
  DROP TYPE "public"."enum_expertise_pages_blocks_feature_tabs_theme";
  DROP TYPE "public"."enum_expertise_pages_blocks_carousel_theme";
  DROP TYPE "public"."enum_expertise_pages_blocks_archive_theme";
  DROP TYPE "public"."enum_expertise_pages_blocks_cta_theme";
  DROP TYPE "public"."enum_expertise_pages_blocks_form_block_theme";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_content_theme";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_media_block_theme";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_feature_statement_grid_theme";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_feature_heading_offset_theme";
  DROP TYPE "public"."enum___expertise_pages_v_image_statement_v_aspect_ratio";
  DROP TYPE "public"."enum___expertise_pages_v_image_statement_v_theme";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_feature_tabs_theme";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_carousel_theme";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_archive_theme";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_cta_theme";
  DROP TYPE "public"."enum__expertise_pages_v_blocks_form_block_theme";
  DROP TYPE "public"."enum_audience_pages_blocks_content_theme";
  DROP TYPE "public"."enum_audience_pages_blocks_media_block_theme";
  DROP TYPE "public"."enum_audience_pages_blocks_feature_statement_grid_theme";
  DROP TYPE "public"."enum_audience_pages_blocks_feature_heading_offset_theme";
  DROP TYPE "public"."enum_audience_pages_image_statement_aspect_ratio";
  DROP TYPE "public"."enum_audience_pages_image_statement_theme";
  DROP TYPE "public"."enum_audience_pages_blocks_feature_tabs_theme";
  DROP TYPE "public"."enum_audience_pages_blocks_carousel_theme";
  DROP TYPE "public"."enum_audience_pages_blocks_archive_theme";
  DROP TYPE "public"."enum_audience_pages_blocks_cta_theme";
  DROP TYPE "public"."enum_audience_pages_blocks_form_block_theme";
  DROP TYPE "public"."enum__audience_pages_v_blocks_content_theme";
  DROP TYPE "public"."enum__audience_pages_v_blocks_media_block_theme";
  DROP TYPE "public"."enum__audience_pages_v_blocks_feature_statement_grid_theme";
  DROP TYPE "public"."enum__audience_pages_v_blocks_feature_heading_offset_theme";
  DROP TYPE "public"."enum___audience_pages_v_image_statement_v_aspect_ratio";
  DROP TYPE "public"."enum___audience_pages_v_image_statement_v_theme";
  DROP TYPE "public"."enum__audience_pages_v_blocks_feature_tabs_theme";
  DROP TYPE "public"."enum__audience_pages_v_blocks_carousel_theme";
  DROP TYPE "public"."enum__audience_pages_v_blocks_archive_theme";
  DROP TYPE "public"."enum__audience_pages_v_blocks_cta_theme";
  DROP TYPE "public"."enum__audience_pages_v_blocks_form_block_theme";
  DROP TYPE "public"."enum_home_blocks_content_theme";
  DROP TYPE "public"."enum_home_blocks_media_block_theme";
  DROP TYPE "public"."enum_home_blocks_feature_statement_grid_theme";
  DROP TYPE "public"."enum_home_blocks_feature_heading_offset_theme";
  DROP TYPE "public"."enum_home_image_statement_aspect_ratio";
  DROP TYPE "public"."enum_home_image_statement_theme";
  DROP TYPE "public"."enum_home_blocks_feature_tabs_theme";
  DROP TYPE "public"."enum_home_blocks_testimonials_marquee_theme";
  DROP TYPE "public"."enum_home_blocks_carousel_theme";
  DROP TYPE "public"."enum_home_blocks_archive_theme";
  DROP TYPE "public"."enum_home_blocks_cta_theme";
  DROP TYPE "public"."enum_home_blocks_form_block_theme";
  DROP TYPE "public"."enum_home_blocks_newsletter_signup_theme";
  DROP TYPE "public"."enum__home_v_blocks_content_theme";
  DROP TYPE "public"."enum__home_v_blocks_media_block_theme";
  DROP TYPE "public"."enum__home_v_blocks_feature_statement_grid_theme";
  DROP TYPE "public"."enum__home_v_blocks_feature_heading_offset_theme";
  DROP TYPE "public"."enum___home_v_image_statement_v_aspect_ratio";
  DROP TYPE "public"."enum___home_v_image_statement_v_theme";
  DROP TYPE "public"."enum__home_v_blocks_feature_tabs_theme";
  DROP TYPE "public"."enum__home_v_blocks_testimonials_marquee_theme";
  DROP TYPE "public"."enum__home_v_blocks_carousel_theme";
  DROP TYPE "public"."enum__home_v_blocks_archive_theme";
  DROP TYPE "public"."enum__home_v_blocks_cta_theme";
  DROP TYPE "public"."enum__home_v_blocks_form_block_theme";
  DROP TYPE "public"."enum__home_v_blocks_newsletter_signup_theme";`)
}
