import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__pages_v_version_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_work_pages_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__work_pages_v_version_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_lab_pages_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__lab_pages_v_version_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_expertise_pages_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__expertise_pages_v_version_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_audience_pages_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__audience_pages_v_version_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  ALTER TYPE "public"."enum_pages_hero_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__pages_v_version_hero_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_work_pages_hero_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__work_pages_v_version_hero_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_lab_pages_hero_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__lab_pages_v_version_hero_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_expertise_pages_hero_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__expertise_pages_v_version_hero_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum_audience_pages_hero_visual_type" ADD VALUE 'lightLeak';
  ALTER TYPE "public"."enum__audience_pages_v_version_hero_visual_type" ADD VALUE 'lightLeak';
  ALTER TABLE "pages" ADD COLUMN "hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_origin" "enum_pages_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "pages" ADD COLUMN "hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_origin" "enum__pages_v_version_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "work_pages" ADD COLUMN "hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "work_pages" ADD COLUMN "hero_shader_origin" "enum_work_pages_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "work_pages" ADD COLUMN "hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_work_pages_v" ADD COLUMN "version_hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_work_pages_v" ADD COLUMN "version_hero_shader_origin" "enum__work_pages_v_version_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_work_pages_v" ADD COLUMN "version_hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "lab_pages" ADD COLUMN "hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "lab_pages" ADD COLUMN "hero_shader_origin" "enum_lab_pages_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "lab_pages" ADD COLUMN "hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_lab_pages_v" ADD COLUMN "version_hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_lab_pages_v" ADD COLUMN "version_hero_shader_origin" "enum__lab_pages_v_version_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_lab_pages_v" ADD COLUMN "version_hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "expertise_pages" ADD COLUMN "hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "expertise_pages" ADD COLUMN "hero_shader_origin" "enum_expertise_pages_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "expertise_pages" ADD COLUMN "hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_expertise_pages_v" ADD COLUMN "version_hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_expertise_pages_v" ADD COLUMN "version_hero_shader_origin" "enum__expertise_pages_v_version_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_expertise_pages_v" ADD COLUMN "version_hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "audience_pages" ADD COLUMN "hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "audience_pages" ADD COLUMN "hero_shader_origin" "enum_audience_pages_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "audience_pages" ADD COLUMN "hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_audience_pages_v" ADD COLUMN "version_hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_audience_pages_v" ADD COLUMN "version_hero_shader_origin" "enum__audience_pages_v_version_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_audience_pages_v" ADD COLUMN "version_hero_shader_show_media" boolean DEFAULT false;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages" ALTER COLUMN "hero_visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_hero_visual_type";
  CREATE TYPE "public"."enum_pages_hero_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "pages" ALTER COLUMN "hero_visual_type" SET DATA TYPE "public"."enum_pages_hero_visual_type" USING "hero_visual_type"::"public"."enum_pages_hero_visual_type";
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_version_hero_visual_type";
  CREATE TYPE "public"."enum__pages_v_version_hero_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_visual_type" SET DATA TYPE "public"."enum__pages_v_version_hero_visual_type" USING "version_hero_visual_type"::"public"."enum__pages_v_version_hero_visual_type";
  ALTER TABLE "work_pages" ALTER COLUMN "hero_visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_work_pages_hero_visual_type";
  CREATE TYPE "public"."enum_work_pages_hero_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "work_pages" ALTER COLUMN "hero_visual_type" SET DATA TYPE "public"."enum_work_pages_hero_visual_type" USING "hero_visual_type"::"public"."enum_work_pages_hero_visual_type";
  ALTER TABLE "_work_pages_v" ALTER COLUMN "version_hero_visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__work_pages_v_version_hero_visual_type";
  CREATE TYPE "public"."enum__work_pages_v_version_hero_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_work_pages_v" ALTER COLUMN "version_hero_visual_type" SET DATA TYPE "public"."enum__work_pages_v_version_hero_visual_type" USING "version_hero_visual_type"::"public"."enum__work_pages_v_version_hero_visual_type";
  ALTER TABLE "lab_pages" ALTER COLUMN "hero_visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_lab_pages_hero_visual_type";
  CREATE TYPE "public"."enum_lab_pages_hero_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "lab_pages" ALTER COLUMN "hero_visual_type" SET DATA TYPE "public"."enum_lab_pages_hero_visual_type" USING "hero_visual_type"::"public"."enum_lab_pages_hero_visual_type";
  ALTER TABLE "_lab_pages_v" ALTER COLUMN "version_hero_visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__lab_pages_v_version_hero_visual_type";
  CREATE TYPE "public"."enum__lab_pages_v_version_hero_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_lab_pages_v" ALTER COLUMN "version_hero_visual_type" SET DATA TYPE "public"."enum__lab_pages_v_version_hero_visual_type" USING "version_hero_visual_type"::"public"."enum__lab_pages_v_version_hero_visual_type";
  ALTER TABLE "expertise_pages" ALTER COLUMN "hero_visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_expertise_pages_hero_visual_type";
  CREATE TYPE "public"."enum_expertise_pages_hero_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "expertise_pages" ALTER COLUMN "hero_visual_type" SET DATA TYPE "public"."enum_expertise_pages_hero_visual_type" USING "hero_visual_type"::"public"."enum_expertise_pages_hero_visual_type";
  ALTER TABLE "_expertise_pages_v" ALTER COLUMN "version_hero_visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__expertise_pages_v_version_hero_visual_type";
  CREATE TYPE "public"."enum__expertise_pages_v_version_hero_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_expertise_pages_v" ALTER COLUMN "version_hero_visual_type" SET DATA TYPE "public"."enum__expertise_pages_v_version_hero_visual_type" USING "version_hero_visual_type"::"public"."enum__expertise_pages_v_version_hero_visual_type";
  ALTER TABLE "audience_pages" ALTER COLUMN "hero_visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_audience_pages_hero_visual_type";
  CREATE TYPE "public"."enum_audience_pages_hero_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "audience_pages" ALTER COLUMN "hero_visual_type" SET DATA TYPE "public"."enum_audience_pages_hero_visual_type" USING "hero_visual_type"::"public"."enum_audience_pages_hero_visual_type";
  ALTER TABLE "_audience_pages_v" ALTER COLUMN "version_hero_visual_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__audience_pages_v_version_hero_visual_type";
  CREATE TYPE "public"."enum__audience_pages_v_version_hero_visual_type" AS ENUM('media', 'streakField');
  ALTER TABLE "_audience_pages_v" ALTER COLUMN "version_hero_visual_type" SET DATA TYPE "public"."enum__audience_pages_v_version_hero_visual_type" USING "version_hero_visual_type"::"public"."enum__audience_pages_v_version_hero_visual_type";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_bleed";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_origin";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_show_media";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_bleed";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_origin";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_show_media";
  ALTER TABLE "work_pages" DROP COLUMN "hero_shader_bleed";
  ALTER TABLE "work_pages" DROP COLUMN "hero_shader_origin";
  ALTER TABLE "work_pages" DROP COLUMN "hero_shader_show_media";
  ALTER TABLE "_work_pages_v" DROP COLUMN "version_hero_shader_bleed";
  ALTER TABLE "_work_pages_v" DROP COLUMN "version_hero_shader_origin";
  ALTER TABLE "_work_pages_v" DROP COLUMN "version_hero_shader_show_media";
  ALTER TABLE "lab_pages" DROP COLUMN "hero_shader_bleed";
  ALTER TABLE "lab_pages" DROP COLUMN "hero_shader_origin";
  ALTER TABLE "lab_pages" DROP COLUMN "hero_shader_show_media";
  ALTER TABLE "_lab_pages_v" DROP COLUMN "version_hero_shader_bleed";
  ALTER TABLE "_lab_pages_v" DROP COLUMN "version_hero_shader_origin";
  ALTER TABLE "_lab_pages_v" DROP COLUMN "version_hero_shader_show_media";
  ALTER TABLE "expertise_pages" DROP COLUMN "hero_shader_bleed";
  ALTER TABLE "expertise_pages" DROP COLUMN "hero_shader_origin";
  ALTER TABLE "expertise_pages" DROP COLUMN "hero_shader_show_media";
  ALTER TABLE "_expertise_pages_v" DROP COLUMN "version_hero_shader_bleed";
  ALTER TABLE "_expertise_pages_v" DROP COLUMN "version_hero_shader_origin";
  ALTER TABLE "_expertise_pages_v" DROP COLUMN "version_hero_shader_show_media";
  ALTER TABLE "audience_pages" DROP COLUMN "hero_shader_bleed";
  ALTER TABLE "audience_pages" DROP COLUMN "hero_shader_origin";
  ALTER TABLE "audience_pages" DROP COLUMN "hero_shader_show_media";
  ALTER TABLE "_audience_pages_v" DROP COLUMN "version_hero_shader_bleed";
  ALTER TABLE "_audience_pages_v" DROP COLUMN "version_hero_shader_origin";
  ALTER TABLE "_audience_pages_v" DROP COLUMN "version_hero_shader_show_media";
  DROP TYPE "public"."enum_pages_hero_shader_origin";
  DROP TYPE "public"."enum__pages_v_version_hero_shader_origin";
  DROP TYPE "public"."enum_work_pages_hero_shader_origin";
  DROP TYPE "public"."enum__work_pages_v_version_hero_shader_origin";
  DROP TYPE "public"."enum_lab_pages_hero_shader_origin";
  DROP TYPE "public"."enum__lab_pages_v_version_hero_shader_origin";
  DROP TYPE "public"."enum_expertise_pages_hero_shader_origin";
  DROP TYPE "public"."enum__expertise_pages_v_version_hero_shader_origin";
  DROP TYPE "public"."enum_audience_pages_hero_shader_origin";
  DROP TYPE "public"."enum__audience_pages_v_version_hero_shader_origin";`)
}
